return {
    [1] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/011.png",
        id = 1,
        icon = "icon/chatBubble/chatUseRes/010.png",
        portraitid = 20000,
    },
    [2] = {
        overturnType = 1,
        othericon = "",
        id = 2,
        icon = "icon/chatBubble/chatUseRes/005.png",
        portraitid = 20001,
    },
    [3] = {
        overturnType = 1,
        othericon = "",
        id = 3,
        icon = "icon/chatBubble/chatUseRes/003.png",
        portraitid = 20002,
    },
    [4] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/008.png",
        id = 4,
        icon = "icon/chatBubble/chatUseRes/007.png",
        portraitid = 20003,
    },
    [5] = {
        overturnType = 1,
        othericon = "",
        id = 5,
        icon = "icon/chatBubble/chatUseRes/009.png",
        portraitid = 20004,
    },
    [6] = {
        overturnType = 1,
        othericon = "",
        id = 6,
        icon = "icon/chatBubble/chatUseRes/006.png",
        portraitid = 20005,
    },
    [7] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/004.png",
        id = 7,
        icon = "icon/chatBubble/chatUseRes/001.png",
        portraitid = 20006,
    },
    [8] = {
        overturnType = 1,
        othericon = "",
        id = 8,
        icon = "icon/chatBubble/chatUseRes/002.png",
        portraitid = 20007,
    },
    [9] = {
        overturnType = 1,
        othericon = "",
        id = 9,
        icon = "icon/chatBubble/chatUseRes/014.png",
        portraitid = 20008,
    },
    [10] = {
        overturnType = 1,
        othericon = "",
        id = 10,
        icon = "icon/chatBubble/chatUseRes/015.png",
        portraitid = 20009,
    },
    [11] = {
        overturnType = 1,
        othericon = "",
        id = 11,
        icon = "icon/chatBubble/chatUseRes/101.png",
        portraitid = 20010,
    },
    [12] = {
        overturnType = 1,
        othericon = "",
        id = 12,
        icon = "icon/chatBubble/chatUseRes/018.png",
        portraitid = 20011,
    },
    [13] = {
        overturnType = 1,
        othericon = "",
        id = 13,
        icon = "icon/chatBubble/chatUseRes/018.png",
        portraitid = 20012,
    },
    [14] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/020.png",
        id = 14,
        icon = "icon/chatBubble/chatUseRes/019.png",
        portraitid = 20013,
    },
}