return {
    [1] = {
        buyEndTime = "",
        id = 1,
        price = {
            [580019] = 15,
        },
        items = {
            [520030] = 2,
            [520031] = 1,
            [520029] = 5,
        },
        buyBeginTime = "",
        name = "低阶突破礼包",
        limitVal = 10,
        limitType = 9,
        order = 2,
        color = 1,
        limitDes = "每月1号重置",
    },
    [2] = {
        buyEndTime = "",
        id = 2,
        price = {
            [580019] = 4,
        },
        items = {
            [555013] = 1,
        },
        buyBeginTime = "",
        name = "羁绊材料礼包",
        limitVal = 25,
        limitType = 9,
        order = 3,
        color = 1,
        limitDes = "每月1号重置",
    },
    [3] = {
        buyEndTime = "",
        id = 3,
        price = {
            [580019] = 15,
        },
        items = {
            [240009] = 1,
        },
        buyBeginTime = "",
        name = "质点材料礼包",
        limitVal = 10,
        limitType = 9,
        order = 4,
        color = 1,
        limitDes = "每月1号重置",
    },
    [4] = {
        buyEndTime = "",
        id = 4,
        price = {
            [580019] = 10,
        },
        items = {
            [510155] = 1,
        },
        buyBeginTime = "",
        name = "金币补给礼包",
        limitVal = 30,
        limitType = 9,
        order = 5,
        color = 1,
        limitDes = "每月1号重置",
    },
    [5] = {
        buyEndTime = "",
        id = 5,
        price = {
            [580019] = 120,
        },
        items = {
            [570033] = 1,
        },
        buyBeginTime = "",
        name = "命运徽章",
        limitVal = 2,
        limitType = 9,
        order = 6,
        color = 2,
        limitDes = "每月1号重置",
    },
    [6] = {
        buyEndTime = "",
        id = 6,
        price = {
            [580019] = 25,
        },
        items = {
            [520033] = 1,
        },
        buyBeginTime = "",
        name = "高阶突破礼包",
        limitVal = 4,
        limitType = 9,
        order = 7,
        color = 2,
        limitDes = "每月1号重置",
    },
    [7] = {
        buyEndTime = "",
        id = 7,
        price = {
            [580019] = 10,
        },
        items = {
            [520021] = 1,
        },
        buyBeginTime = "",
        name = "精华礼包",
        limitVal = 10,
        limitType = 9,
        order = 8,
        color = 2,
        limitDes = "每月1号重置",
    },
    [8] = {
        buyEndTime = "",
        id = 8,
        price = {
            [580019] = 2000,
        },
        items = {
            [410504] = 1,
        },
        buyBeginTime = "",
        name = "礼服奖励",
        limitVal = 1,
        limitType = 3,
        order = 9,
        color = 2,
        limitDes = "只能购买1次",
    },
    [9] = {
        buyEndTime = "",
        id = 9,
        price = {
            [580019] = 280,
        },
        items = {
            [599501] = 200,
            [599704] = 1,
        },
        buyBeginTime = "",
        name = "夏拉姆礼包",
        limitVal = 2,
        limitType = 9,
        order = 10,
        color = 2,
        limitDes = "每月1号重置",
    },
    [10] = {
        buyEndTime = "",
        id = 10,
        price = {
            [580019] = 2000,
        },
        items = {
            [411301] = 1,
        },
        buyBeginTime = "",
        name = "七罪时装",
        limitVal = 1,
        limitType = 3,
        order = 11,
        color = 2,
        limitDes = "只能购买1次",
    },
    [11] = {
        buyEndTime = "",
        id = 11,
        price = {
            [580019] = 500,
        },
        items = {
            [524007] = 1,
        },
        buyBeginTime = "",
        name = "重铸礼包",
        limitVal = 3,
        limitType = 9,
        order = 1,
        color = 2,
        limitDes = "每月1号重置",
    },
    [12] = {
        buyEndTime = "",
        id = 12,
        price = {
            [580019] = 2000,
        },
        items = {
            [410209] = 1,
        },
        buyBeginTime = "",
        name = "神威灵装一番",
        limitVal = 1,
        limitType = 3,
        order = 12,
        color = 2,
        limitDes = "只能购买1次",
    },
}