local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-playerRegressGiftView_playerRegress_activity_Game",
			UUID = "55f9c4a7_6dd2_4939_a0fe_02ca15364846",
			anchorPoint = "False",
			anchorPointX = "0.5",
			anchorPointY = "0.5",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "548",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "888",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
					UUID = "a3c2eecc_cf80_44a0_9a2f_1885ff92cde5",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_diban_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "96b0490f_9aec_4fc5_a5a3_8366ca5a3a6f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "547",
							ignoreSize = "True",
							name = "Image_diban",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/playerRegress/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							width = "891",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_returnGiftView_1_Image_diban_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
									UUID = "8d6c17f0_4174_4d06_a4a1_fd3176137e1c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "44",
									ignoreSize = "True",
									name = "Image_returnGiftView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/playerRegress/timeBg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -5,
										PositionY = 248,
									},
									visible = "False",
									width = "879",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_poster_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "729a68ed_ab17_4b2f_8c48_74d8cb870281",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "True",
							name = "img_poster",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/playerRegress/gift/02.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -3,
								PositionY = 192,
							},
							width = "855",
							ZOrder = "1",
						},
						{
							controlID = "listView_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "e9074f5a_54df_4133_99be_3c512c5ab4a9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "335",
							ignoreSize = "False",
							innerHeight = "335",
							innerWidth = "845",
							name = "listView",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -3,
								PositionY = -49,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "845",
							ZOrder = "1",
						},
						{
							controlID = "act_timeTxt_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "e6bc710a_3ea6_41c8_9a02_e6b2e3839d92",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF6773B2",
								StrokeSize = 2,
							},
							height = "31",
							ignoreSize = "True",
							name = "act_timeTxt",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "活动时间：",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -340,
								PositionY = 249,
							},
							visible = "False",
							width = "99",
							ZOrder = "1",
						},
						{
							controlID = "act_time_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "4594857a_b3da_4d62_9695_82d4d7969b11",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "23",
							ignoreSize = "True",
							name = "act_time",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "20200416",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 212,
								PositionY = 142,
							},
							width = "86",
							ZOrder = "1",
						},
						{
							controlID = "btn_rule_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "eef60ed3_0aa6_4b81_8ff4_a70912553f60",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "42",
							ignoreSize = "True",
							name = "btn_rule",
							normal = "ui/summon/002.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 404,
								PositionY = 247,
							},
							UItype = "Button",
							visible = "False",
							width = "46",
							ZOrder = "1",
						},
						{
							controlID = "btn_jump_Panel_root_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "7f753303_ba9e_454f_8a4d_df08e70d25d8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "46",
							ignoreSize = "True",
							name = "btn_jump",
							normal = "ui/activity/playerRegress/gift/01.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 338,
								PositionY = -239,
							},
							UItype = "Button",
							width = "186",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
					UUID = "2112a409_76ce_4ca4_8b23_8e7ee5c2e688",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -460,
						PositionY = -1044,
						LeftPositon = 1148,
						TopPosition = 301,
						relativeToName = "Panel",
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
							UUID = "ed2faa17_1f92_4125_b97b_4e10daa7d37d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFFA500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "335",
							ignoreSize = "False",
							name = "panel_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 203,
								PositionY = 289,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "271",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
									UUID = "97ba425d_8f1c_4b8c_93b7_f2b959da2a14",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "335",
									ignoreSize = "True",
									name = "Image_diban",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/playerRegress/gift/03.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "271",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_name_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
											UUID = "973676f0_4ffb_49a1_830e_03e0d12ee171",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "第一天",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 142,
											},
											width = "76",
											ZOrder = "1",
										},
										{
											controlID = "panel_gifts_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
											UUID = "5aebd418_9fce_4add_9fa8_dbbc65ac7937",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "200",
											ignoreSize = "False",
											name = "panel_gifts",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 14,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "253",
											ZOrder = "1",
										},
										{
											controlID = "btn_buy_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
											UUID = "4ca52068_e4d4_484b_9210_13e129db072b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "25",
											HitType = 
											{
												nHitType = 1,
												nXpos = -28,
												nYpos = -18,
												nHitWidth = 124,
												nHitHeight = 68
											},
											ignoreSize = "True",
											name = "btn_buy",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 67,
												PositionY = -135,
											},
											UItype = "Button",
											width = "60",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_returnGiftView_1_btn_buy_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
													UUID = "9e9229d9_09ea_4fb1_a8a1_589ddcaa1eb3",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF3A4DA9",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "30",
													ignoreSize = "True",
													name = "Label_returnGiftView_1",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "购买",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													visible = "False",
													width = "51",
													ZOrder = "1",
												},
												{
													controlID = "Label_tips_btn_buy_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
													UUID = "2089a467_b9ed_48a3_a24c_4fc7663dfb53",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF7275D0",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_tips",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "限购次数",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -144,
														PositionY = 17,
													},
													width = "84",
													ZOrder = "1",
												},
												{
													controlID = "Label_leftTime_btn_buy_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
													UUID = "3d998d29_a3f1_4a33_b9b7_f068079448db",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF7275D0",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_leftTime",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "1 2",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -150,
														PositionY = -12,
													},
													width = "33",
													ZOrder = "1",
												},
												{
													controlID = "Label_price_btn_buy_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
													UUID = "336f31cd_3333_4720_bcab_84ed44a296c4",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "28",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "35",
													ignoreSize = "True",
													name = "Label_price",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "¥99",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 2,
														PositionY = 2,
													},
													width = "73",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_exchange_Label_price_btn_buy_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
															UUID = "5a593051_7be6_41cb_8a2c_f494ad534a2b",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "30",
															ignoreSize = "False",
															name = "Image_exchange",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = -57,
																PositionY = 1,
															},
															width = "30",
															ZOrder = "1",
														},
													},
												},
											},
										},
										{
											controlID = "img_hadGetted_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
											UUID = "e89e72d2_4d94_40c1_8b4e_35c9700f62dd",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "55",
											ignoreSize = "True",
											name = "img_hadGetted",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											texturePath = "ui/activity/playerRegress/login/02.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -131,
											},
											visible = "False",
											width = "143",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "lab_hadGetted_img_hadGetted_Image_diban_panel_item_Panel_prefab_Panel-playerRegressGiftView_playerRegress_activity_Game",
													UUID = "30f1c66c_76bf_4e6f_aa94_f0e3b56fa999",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "30",
													ignoreSize = "True",
													name = "lab_hadGetted",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "已购买",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "76",
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/playerRegress/bg.png",
			"ui/activity/playerRegress/timeBg.png",
			"ui/activity/playerRegress/gift/02.png",
			"ui/summon/002.png",
			"ui/activity/playerRegress/gift/01.png",
			"ui/activity/playerRegress/gift/03.png",
			"ui/activity/playerRegress/login/02.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

