local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-playerRegressTaskView_playerRegress_activity_Game",
			UUID = "1c176434_36df_488c_b031_65423183af62",
			anchorPoint = "False",
			anchorPointX = "0.5",
			anchorPointY = "0.5",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "548",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "888",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
					UUID = "c4df708b_e3d6_4ff1_8e6d_aa8382c644f3",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_diban_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "4265f353_a090_46d2_af26_b0836cdd5f5e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "547",
							ignoreSize = "True",
							name = "Image_diban",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/playerRegress/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							width = "891",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_returnGiftView_1_Image_diban_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
									UUID = "2dee657e_cff7_4c49_88de_696f46be4f92",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "44",
									ignoreSize = "True",
									name = "Image_returnGiftView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/playerRegress/timeBg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -5,
										PositionY = 250,
									},
									width = "879",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_playerRegressTaskView_1_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "c1227e5a_5418_4ab1_899e_b0833cfd7244",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "True",
							name = "Image_playerRegressTaskView_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/playerRegress/task/2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -4,
								PositionY = 165,
							},
							width = "862",
							ZOrder = "1",
						},
						{
							controlID = "Label_playerRegressTaskView_1_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "694247f5_f790_4dbf_a7fd_f31238eeac7f",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "27",
							ignoreSize = "True",
							name = "Label_playerRegressTaskView_1",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "当前活跃值",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -402,
								PositionY = 178,
							},
							width = "123",
							ZOrder = "1",
						},
						{
							controlID = "lab_acyivityNum_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "62eb795a_076c_4f2d_83e7_b1798461225e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFBE76E",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "27",
							ignoreSize = "True",
							name = "lab_acyivityNum",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "1000",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -227,
								PositionY = 178,
							},
							width = "70",
							ZOrder = "1",
						},
						{
							controlID = "ScrollView_topAward_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "19506136_a445_4829_8540_8bbe19ac5a34",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "120",
							ignoreSize = "False",
							innerHeight = "120",
							innerWidth = "1100",
							name = "ScrollView_topAward",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -174,
								PositionY = 114,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "597",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "panel_topProgress_ScrollView_topAward_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
									UUID = "2b1a5611_5fe6_4159_af0a_cef367ea507f",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "88",
									ignoreSize = "False",
									name = "panel_topProgress",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -6,
										PositionY = 25,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "1100",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "img_progressBg_panel_topProgress_ScrollView_topAward_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "a584aa94_29ee_412f_9642_9780c4a8a3fc",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "18",
											ignoreSize = "False",
											name = "img_progressBg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/playerRegress/task/3.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 15,
												PositionY = 39,
											},
											width = "1050",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "bar_progress_img_progressBg_panel_topProgress_ScrollView_topAward_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
													UUID = "f46790a8_b07c_40c7_906e_dda40f97ddfe",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
													classname = "MELoadingBar",
													direction = "0",
													dstBlendFunc = "771",
													height = "24",
													ignoreSize = "False",
													name = "bar_progress",
													percent = "100",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texture = "ui/activity/playerRegress/task/4.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 523,
													},
													width = "1050",
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
						{
							controlID = "listView_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "db0de01a_8a95_4d57_8b7b_eeae92ace248",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "365",
							ignoreSize = "False",
							innerHeight = "365",
							innerWidth = "860",
							name = "listView",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -6,
								PositionY = -76,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "860",
							ZOrder = "1",
						},
						{
							controlID = "act_timeTxt_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "e1f96f7a_fdbb_463f_87da_c6459c0971ea",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF6773B2",
								StrokeSize = 2,
							},
							height = "31",
							ignoreSize = "True",
							name = "act_timeTxt",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "活动时间：",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -340,
								PositionY = 249,
							},
							width = "99",
							ZOrder = "1",
						},
						{
							controlID = "act_time_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "38d4de27_65a0_42b9_8dac_625a8d5fdc54",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF6773B2",
								StrokeSize = 2,
							},
							height = "31",
							ignoreSize = "True",
							name = "act_time",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "20200416",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -284,
								PositionY = 249,
							},
							width = "145",
							ZOrder = "1",
						},
						{
							controlID = "btn_rule_Panel_root_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "2df5016a_f3d4_46f6_898e_d1456954e259",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "42",
							ignoreSize = "True",
							name = "btn_rule",
							normal = "ui/summon/002.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 404,
								PositionY = 247,
							},
							UItype = "Button",
							visible = "False",
							width = "46",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
					UUID = "2f470660_f704_47f6_a629_985d25cefdef",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -460,
						PositionY = -1044,
						LeftPositon = 1148,
						TopPosition = 301,
						relativeToName = "Panel",
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "ef8b8ee5_50da_47a2_8892_853bb9dbc43b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFFA500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "365",
							ignoreSize = "False",
							name = "panel_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 203,
								PositionY = 289,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "203",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
									UUID = "ecf63f38_be45_4e73_8db7_6cd2c59d21ef",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "365",
									ignoreSize = "True",
									name = "Image_diban",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/playerRegress/task/5.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "203",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_name_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "bec6132f_f551_4e5b_b001_91cb2dd3c10d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "礼包名称",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 157,
											},
											width = "91",
											ZOrder = "1",
										},
										{
											controlID = "lab_desc_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "bc33f44c_6be7_47c0_b30b_bdab7badeebc",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "46",
											ignoreSize = "False",
											name = "lab_desc",
											nTextAlign = "0",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "描述，描述述描述描述描述描述描述",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 109,
											},
											width = "194",
											ZOrder = "1",
										},
										{
											controlID = "panel_gifts_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "60e96fcf_41bb_458a_9ee5_0c210142e3fe",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "203",
											ignoreSize = "False",
											name = "panel_gifts",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 6,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "199",
											ZOrder = "1",
										},
										{
											controlID = "btn_go_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "ba530cdd_5eb2_4d5c_8732_84381deea868",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "50",
											ignoreSize = "True",
											name = "btn_go",
											normal = "ui/activity/playerRegress/01.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionY = -156,
											},
											UItype = "Button",
											visible = "False",
											width = "199",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_returnGiftView_1_btn_go_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
													UUID = "ee422158_1b39_4f32_a260_fd00a51a3a71",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "28",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "35",
													ignoreSize = "True",
													name = "Label_returnGiftView_1",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "前往",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "59",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "btn_getReward_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "88011806_bf7a_4083_87eb_0034b9ef0321",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "50",
											ignoreSize = "True",
											name = "btn_getReward",
											normal = "ui/activity/playerRegress/02.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionY = -156,
											},
											UItype = "Button",
											visible = "False",
											width = "199",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_returnGiftView_1_btn_getReward_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
													UUID = "6fb53145_83f7_4386_afe0_4fcb159939b1",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF7275D0",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "28",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "35",
													ignoreSize = "True",
													name = "Label_returnGiftView_1",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "领取",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "59",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "img_hadGetted_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "29dbecf9_4df6_4e0a_93c5_b57b9e0b27a7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "50",
											ignoreSize = "True",
											name = "img_hadGetted",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											texturePath = "ui/activity/playerRegress/02.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -155,
											},
											width = "199",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "lab_hadGetted_img_hadGetted_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
													UUID = "2175be0d_809c_4930_80c2_c73a0d650051",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF7275D0",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "28",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "35",
													ignoreSize = "True",
													name = "lab_hadGetted",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "已领取",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "87",
													ZOrder = "1",
												},
												{
													controlID = "Image_playerRegressTaskView_1_img_hadGetted_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
													UUID = "edb3c27c_2c1a_4d1b_a492_66501c11b26b",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "365",
													ignoreSize = "False",
													name = "Image_playerRegressTaskView_1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/activity/playerRegress/03.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = 155,
													},
													width = "203",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "lab_specialId_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "032fd48a_0b49_41fb_8a88_610d9b7dc2cc",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "lab_specialId",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "30",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 22,
												PositionY = -114,
											},
											width = "25",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_playerRegressTaskView_1_lab_specialId_Image_diban_panel_item_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
													UUID = "2fc0fc56_855e_4dba_876b_4033d988fb09",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "23",
													ignoreSize = "True",
													name = "Label_playerRegressTaskView_1",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "活跃度+",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -37,
													},
													width = "75",
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
						{
							controlID = "panel_progressItem_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
							UUID = "ab69fa3f_85f0_46f5_bfc5_2d4aef87c3c9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "82",
							ignoreSize = "False",
							name = "panel_progressItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 601,
								PositionY = 207,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "67",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_getted_panel_progressItem_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
									UUID = "78c8159d_80b9_4d49_84cf_e82bf1327a70",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "79",
									ignoreSize = "True",
									name = "img_getted",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/rerurnGift/lh003.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
									},
									width = "76",
									ZOrder = "1",
								},
								{
									controlID = "img_canGet_panel_progressItem_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
									UUID = "1802125a_ed42_4ac0_8180_2a6b583e5255",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "79",
									ignoreSize = "True",
									name = "img_canGet",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/rerurnGift/lh002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
									},
									visible = "False",
									width = "76",
									ZOrder = "1",
								},
								{
									controlID = "img_ing_panel_progressItem_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
									UUID = "2f2774f0_382d_443a_82af_996adbb5f4e3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "79",
									ignoreSize = "True",
									name = "img_ing",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/rerurnGift/lh001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
									},
									width = "76",
									ZOrder = "1",
								},
								{
									controlID = "Image_returnGiftView_1_panel_progressItem_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
									UUID = "b7a3c14a_e7d9_4ba1_9d7a_ace3157d83a6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "23",
									ignoreSize = "False",
									name = "Image_returnGiftView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/playerRegress/task/1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -45,
									},
									width = "46",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "lab_needNum_Image_returnGiftView_1_panel_progressItem_Panel_prefab_Panel-playerRegressTaskView_playerRegress_activity_Game",
											UUID = "e5b454e0_8cd4_4611_bd43_243b29c9af2c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "lab_needNum",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "100",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -3,
											},
											width = "32",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/playerRegress/bg.png",
			"ui/activity/playerRegress/timeBg.png",
			"ui/activity/playerRegress/task/2.png",
			"ui/activity/playerRegress/task/3.png",
			"ui/activity/playerRegress/task/4.png",
			"ui/summon/002.png",
			"ui/activity/playerRegress/task/5.png",
			"ui/activity/playerRegress/01.png",
			"ui/activity/playerRegress/02.png",
			"ui/activity/playerRegress/03.png",
			"ui/activity/rerurnGift/lh003.png",
			"ui/activity/rerurnGift/lh002.png",
			"ui/activity/rerurnGift/lh001.png",
			"ui/activity/playerRegress/task/1.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

