local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
			UUID = "2d01396f_1035_4461_9b5f_8f1e98c15be9",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
					UUID = "4e9f0b3f_70c7_4a35_b8ed_9f466e9627ca",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
							UUID = "68fd993e_9e42_4726_b277_b784a05f29ef",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/onlineteam/BG.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_fubenEndlessPlusSquadView_1_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "ead9d86d_6dd9_400a_bd61_1d7d7c6e6527",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "2",
									ignoreSize = "True",
									name = "Image_fubenEndlessPlusSquadView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									texturePath = "ui/fuben/endless_plus/备战界面.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "2",
									ZOrder = "1",
								},
								{
									controlID = "Image_hero_bg_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "6610aab9_6944_4f79_99ad_216f793992b0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "430",
									ignoreSize = "False",
									name = "Image_hero_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/012.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -554,
										PositionY = -235,
									},
									width = "600",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "ScrollView_hero_Image_hero_bg_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "585bb714_c522_4017_83b5_30b63b8ce99a",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "1",
											dstBlendFunc = "771",
											height = "430",
											ignoreSize = "False",
											innerHeight = "430",
											innerWidth = "580",
											name = "ScrollView_hero",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 8,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "580",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_level_bg_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "c3a997a3_5242_4133_945a_e553fa30807b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "300",
									ignoreSize = "False",
									name = "Image_level_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/011.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 311,
										PositionY = -84,
									},
									visible = "False",
									width = "490",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_level_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "875368a4_85eb_4d03_8c5f_b5a11d9ae7a6",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "290",
									ignoreSize = "False",
									innerHeight = "290",
									innerWidth = "480",
									name = "ScrollView_level",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 69,
										PositionY = -229,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "480",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_buff_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "86fa6f6a_6faf_41cb_ae14_aec7a73e668a",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "2",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									innerHeight = "80",
									innerWidth = "374",
									name = "ScrollView_buff",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 86,
										PositionY = 111,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "374",
									ZOrder = "1",
								},
								{
									controlID = "Button_fight_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "1a5ecf48_4587_4cf0_8e79_a9ba43fb8e68",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "58",
									ignoreSize = "True",
									name = "Button_fight",
									normal = "ui/common/button_big_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 483,
										PositionY = -272,
									},
									UItype = "Button",
									width = "134",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_btn_Button_fight_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "a8e43727_8c57_473f_975a_2f4e61e8fe32",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_btn",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "开始挑战",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "106",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_level_desc_tip_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "8cff9ef4_34e2_4236_8680_7cfc4fc5bfb1",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "18",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "21",
									ignoreSize = "True",
									name = "Label_level_desc_tip",
									nTextAlign = "0",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "当前通关时间：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 187,
										PositionY = 194,
									},
									visible = "False",
									width = "117",
									ZOrder = "1",
								},
								{
									controlID = "Label_level_desc_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "61a93270_c912_4ff6_86fa_996ecb6bd0fc",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "18",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "21",
									ignoreSize = "True",
									name = "Label_level_desc",
									nTextAlign = "0",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "25",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 305,
										PositionY = 193,
									},
									visible = "False",
									width = "22",
									ZOrder = "1",
								},
								{
									controlID = "Button_sort_order_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "2f0a52d5_d9cc_4fc5_98e7_b360bb5f3be7",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "50",
									ignoreSize = "True",
									name = "Button_sort_order",
									normal = "ui/onlineteam/preteam/4.png",
									pressed = "ui/onlineteam/preteam/4.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 45,
										PositionY = 226,
									},
									UItype = "Button",
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_order_arrow_Button_sort_order_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "de94a69f_8ab2_4846_8526_cbc49249cdae",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "1",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "15",
											ignoreSize = "True",
											name = "Image_order_arrow",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/onlineteam/preteam/5.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -6,
												PositionY = 21,
											},
											width = "12",
											ZOrder = "1",
										},
										{
											controlID = "Label_order_name_Button_sort_order_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "cd5bd586_59d8_4996_9d5e_7eff86e46fff",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFA2A4CB",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_order_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "升  序",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -75,
												IsPercent = true,
												PercentX = -50,
											},
											width = "59",
											ZOrder = "1",
										},
										{
											controlID = "Image_order_icon_Button_sort_order_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "c11e534c_15cc_4778_921c_fd9066280d22",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "20",
											ignoreSize = "True",
											name = "Image_order_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/bag/new_ui/new_08.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -20,
											},
											visible = "False",
											width = "30",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_rule_Button_sort_order_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "9d336c75_70fd_49b6_8619_2f5c287e609d",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "1",
											dstBlendFunc = "771",
											height = "175",
											ignoreSize = "False",
											innerHeight = "175",
											innerWidth = "151",
											name = "ScrollView_rule",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -150,
												PositionY = -203,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "151",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_title1_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "445c5b65_2004_415f_87f0_b7b7103c9eff",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "39",
									ignoreSize = "True",
									name = "Image_title1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -449,
										PositionY = 219,
									},
									width = "210",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_fubenEndlessPlusView_1_Image_title1_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "f6dde873_12dd_4485_86ba_97e901b9500d",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "Label_fubenEndlessPlusView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "精灵选择",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -97,
												PositionY = -1,
											},
											width = "107",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_title2_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "7e72523e_ece1_43b3_b371_284fc174c106",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "39",
									ignoreSize = "True",
									name = "Image_title2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 170,
										PositionY = 87,
									},
									width = "210",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_floor_name_Image_title2_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "fb0d596f_d443_412a_b941_47a1638e720e",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_floor_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "队伍配置",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -90,
												PositionY = -3,
											},
											width = "92",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_title3_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "ba16c653_d15f_4e1f_a6af_5fabd7393a5e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "39",
									ignoreSize = "True",
									name = "Image_title3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 172,
										PositionY = 218,
									},
									width = "210",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_title3_Image_title3_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "993751b3_2050_4878_9a85_fc3633b2a95b",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_title3",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "BUFF",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -95,
												PositionY = -1,
											},
											width = "86",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_check_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "fe5cac26_05a9_44e3_9939_881d1892f618",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "68",
									ignoreSize = "True",
									name = "Button_check",
									normal = "ui/fuben/endless_plus/005.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -457,
										PositionY = -276,
									},
									UItype = "Button",
									width = "201",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_btn_Button_check_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "6ddbcb0b_12a4_4a7d_861b_957ab702e431",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_btn",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "精灵详情",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 29,
											},
											width = "107",
											ZOrder = "1",
										},
										{
											controlID = "Image_fubenEndlessPlusSquadView_1_Button_check_Image_bg_Panel_root_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "09843450_533b_4b00_bd3a_64cdcfa2b363",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "70",
											ignoreSize = "True",
											name = "Image_fubenEndlessPlusSquadView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/new_ui/btn_sprite.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -58,
											},
											width = "70",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
					UUID = "49ae8e1e_2f7a_4279_94f8_fc44f008dfe1",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 567,
						PositionY = -441,
						TopPosition = 761,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_hero_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
							UUID = "d39a94fe_0c06_4967_bd7c_5f22f97d8492",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "120",
							ignoreSize = "False",
							name = "Panel_hero_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -556,
								PositionY = 7,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "115",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_fairyMain_1_Panel_hero_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "bf11fa96_cce2_4c0c_8e03_6af99c976653",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "98",
									ignoreSize = "False",
									name = "Panel_fairyMain_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -41,
										PositionY = -48,
										relativeToName = "Panel",
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "98",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_icon_Panel_fairyMain_1_Panel_hero_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "6b0f7830_601f_42d0_a160_7ce1fdfb2f13",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "92",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/hero/face/1101011.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 18,
												PositionY = 48,
											},
											width = "156",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_over_lock_Panel_hero_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "9bad6881_5a33_4d6a_97b6_1d5d6394223b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "99",
									ignoreSize = "False",
									name = "Image_over_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/new_ui/new_18.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 6,
									},
									width = "99",
									ZOrder = "1",
								},
								{
									controlID = "Image_select_Panel_hero_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "abf8c678_1a90_4e3b_8a85_91c9aa475a33",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "54",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/selected.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 41,
										PositionY = 38,
										IsPercent = true,
										PercentX = 35.92,
										PercentY = 32.22,
									},
									width = "54",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
							UUID = "4f192ea2_0cd3_46ef_acf7_30f27e656c3c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "75",
							ignoreSize = "False",
							name = "Panel_level_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 15,
								PositionY = -214,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "480",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "5d3b953d_4fea_4a4a_b5a7_879c93a63686",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "72",
									ignoreSize = "False",
									name = "Image_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "480",
									ZOrder = "1",
								},
								{
									controlID = "Image_select_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "14962d1b_bc77_4b1a_b834_857f2818c8ff",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "72",
									ignoreSize = "False",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/009.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										
									},
									width = "480",
									ZOrder = "1",
								},
								{
									controlID = "Label_level_name_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "dd9dd8db_6c7d_42d0_a3d0_0656df72ec97",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#00FFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_level_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "TextLable",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -222,
										PositionY = 2,
									},
									width = "135",
									ZOrder = "1",
								},
								{
									controlID = "Image_frame_1_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "6b77c633_ef3e_4761_97c2_f9bf2f8e9e8a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "62",
									ignoreSize = "False",
									name = "Image_frame_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/new_ui/new_18.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -78,
										PositionY = -1,
									},
									width = "62",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_add_Image_frame_1_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "6a1ad84a_8018_4a54_bbfe_de8f7f8ac76b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "60",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/endless_plus/010.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "60",
											ZOrder = "1",
										},
										{
											controlID = "Panel_hero_item_1_Image_frame_1_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "6f252954_491d_4e2c_b47d_7c69aec505b9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "92",
											ignoreSize = "False",
											name = "Panel_hero_item_1",
											scaleX = "0.68",
											scaleY = "0.68",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "92",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Panel_fairyMain_1_Panel_hero_item_1_Image_frame_1_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
													UUID = "1082798b_e2d8_44d5_ac14_94c81da498d9",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "True",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "90",
													ignoreSize = "False",
													name = "Panel_fairyMain_1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = -43,
														PositionY = -45,
														relativeToName = "Panel",
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "90",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_icon_Panel_fairyMain_1_Panel_hero_item_1_Image_frame_1_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
															UUID = "cc4e5898_6219_4292_94ca_0345fb9ee347",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "52",
															ignoreSize = "True",
															name = "Image_icon",
															scaleX = "0.95",
															scaleY = "0.95",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "icon/hero/smallface/10101.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 12,
																PositionY = 45,
															},
															width = "52",
															ZOrder = "1",
														},
													},
												},
											},
										},
									},
								},
								{
									controlID = "Image_frame_2_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "95f7e5ef_ae88_4a61_94cc_c3b78430f0dc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "62",
									ignoreSize = "False",
									name = "Image_frame_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/new_ui/new_18.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -4,
										PositionY = -2,
									},
									width = "62",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_add_Image_frame_2_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "fe2b2530_bd80_49c9_b609_8194a3a05398",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "60",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/endless_plus/010.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "60",
											ZOrder = "1",
										},
										{
											controlID = "Panel_hero_item_1_Image_frame_2_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "74f83b0c_46a5_4171_95c6_c0b2d841634b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "92",
											ignoreSize = "False",
											name = "Panel_hero_item_1",
											scaleX = "0.68",
											scaleY = "0.68",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "92",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Panel_fairyMain_1_Panel_hero_item_1_Image_frame_2_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
													UUID = "69ec1f16_68e7_4b0a_b5a9_db5da0ac71f0",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "True",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "90",
													ignoreSize = "False",
													name = "Panel_fairyMain_1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = -43,
														PositionY = -45,
														relativeToName = "Panel",
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "90",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_icon_Panel_fairyMain_1_Panel_hero_item_1_Image_frame_2_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
															UUID = "b35b4ffb_d489_4d76_9785_f76b5b9de98c",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "52",
															ignoreSize = "True",
															name = "Image_icon",
															scaleX = "0.95",
															scaleY = "0.95",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "icon/hero/smallface/10101.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 12,
																PositionY = 45,
															},
															width = "52",
															ZOrder = "1",
														},
													},
												},
											},
										},
									},
								},
								{
									controlID = "Image_frame_3_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "f983df8c_2f6c_4445_b669_34fe370835cb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "62",
									ignoreSize = "False",
									name = "Image_frame_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/new_ui/new_18.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 68,
										PositionY = -2,
									},
									width = "62",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_add_Image_frame_3_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "73ac1cc4_f9aa_4fdd_a449_7f310051eda6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "60",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/endless_plus/010.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "60",
											ZOrder = "1",
										},
										{
											controlID = "Panel_hero_item_1_Image_frame_3_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "a8b6fec2_2dcc_42ff_9d2f_580a23eb3843",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "92",
											ignoreSize = "False",
											name = "Panel_hero_item_1",
											scaleX = "0.68",
											scaleY = "0.68",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "92",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Panel_fairyMain_1_Panel_hero_item_1_Image_frame_3_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
													UUID = "42bf4a99_b8bd_430e_8609_a819596834a2",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "True",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "90",
													ignoreSize = "False",
													name = "Panel_fairyMain_1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = -43,
														PositionY = -45,
														relativeToName = "Panel",
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "90",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_icon_Panel_fairyMain_1_Panel_hero_item_1_Image_frame_3_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
															UUID = "68316e43_ca88_409d_a95c_b6a7e7906ad4",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "52",
															ignoreSize = "True",
															name = "Image_icon",
															scaleX = "0.95",
															scaleY = "0.95",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "icon/hero/smallface/10101.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 12,
																PositionY = 45,
															},
															width = "52",
															ZOrder = "1",
														},
													},
												},
											},
										},
									},
								},
								{
									controlID = "Button_check_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "61d36636_56f7_44fe_9691_c1eb43458942",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "45",
									ignoreSize = "False",
									name = "Button_check",
									normal = "ui/common/button_big_blue_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 168,
										PositionY = -1,
									},
									UItype = "Button",
									width = "130",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_fubenEndlessPlusSquadView_1_Button_check_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
											UUID = "c43ea721_ea87_4571_a2e1_2635342914e4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_fubenEndlessPlusSquadView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "关卡怪物配置",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 1,
											},
											width = "123",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Button_rule_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
							UUID = "6659fd29_e451_4778_8c25_698305458bb9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "50",
							ignoreSize = "True",
							name = "Button_rule",
							normal = "ui/onlineteam/preteam/4.png",
							pressed = "ui/onlineteam/preteam/4.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 695,
								PositionY = -48,
								LeftPositon = 620,
								TopPosition = 663,
								relativeToName = "Panel",
							},
							UItype = "Button",
							width = "150",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_btn_name_Button_rule_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "d60185c3_2e26_4cc8_b835_b59c8162be80",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFA2A4CB",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_btn_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "升  序",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -14,
										PositionY = -1,
									},
									width = "59",
									ZOrder = "1",
								},
								{
									controlID = "Image_btn_icon_Button_rule_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "5eae5df7_a9ce_4918_85f2_db978cef6e88",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "22",
									ignoreSize = "True",
									name = "Image_btn_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/onlineteam/preteam/7.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 51,
									},
									width = "15",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_buff_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
							UUID = "5a38c883_9fd0_4245_8a17_07723e3a333a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FF191970;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "80",
							ignoreSize = "False",
							name = "Panel_buff",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_buff_Panel_buff_Panel_prefab_Panel-fubenEndlessPlusSquadView_Layer1_fuben_Game",
									UUID = "dcbe72a6_6cd4_4ce2_97af_f45f0111a588",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_buff",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/affix/affix_1_jiansu.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "110",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/onlineteam/BG.png",
			"ui/fuben/endless_plus/备战界面.png",
			"ui/fuben/endless_plus/012.png",
			"ui/fuben/endless_plus/011.png",
			"ui/common/button_big_n.png",
			"ui/onlineteam/preteam/4.png",
			"ui/onlineteam/preteam/5.png",
			"ui/bag/new_ui/new_08.png",
			"ui/fuben/endless_plus/001.png",
			"ui/fuben/endless_plus/005.png",
			"ui/mainLayer/new_ui/btn_sprite.png",
			"icon/hero/face/1101011.png",
			"ui/fairy/new_ui/new_18.png",
			"ui/common/selected.png",
			"ui/fuben/endless_plus/008.png",
			"ui/fuben/endless_plus/009.png",
			"ui/fuben/endless_plus/010.png",
			"icon/hero/smallface/10101.png",
			"ui/common/button_big_blue_n.png",
			"ui/onlineteam/preteam/7.png",
			"icon/affix/affix_1_jiansu.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

