local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-fubenEndlessPlusView_Layer1_fuben_Game",
			UUID = "73e5318c_673c_45b9_a651_0f888c897411",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
					UUID = "08f75e1d_bd2f_45ac_bcb2_3fb16fe5b458",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 510,
						PositionY = 359,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
							UUID = "6c36ba6e_d4ad_4028_97a0_4ddaed5b1e21",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/onlineteam/BG.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_fubenEndlessPlusView_1_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "f60d2be2_d2f4_46d6_bd97_928708b8611a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "2",
									ignoreSize = "True",
									name = "Image_fubenEndlessPlusView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									texturePath = "ui/fuben/endless_plus/主界面.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "2",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_floor_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "9f75e9ea_f8f3_4099_b8ec_a97ea6575461",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "420",
									ignoreSize = "False",
									innerHeight = "420",
									innerWidth = "448",
									name = "ScrollView_floor",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 107,
										PositionY = -225,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "448",
									ZOrder = "1",
								},
								{
									controlID = "Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "a8ffce4e_5a62_4c0f_bca4_6729b4a86969",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "570",
									ignoreSize = "False",
									name = "Panel_right",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -565,
										PositionY = -320,
										IsPercent = true,
										PercentX = -40.75,
										PercentY = -49.95,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "670",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_right_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "a58d7d44_653f_4625_ad02_81dfc3146751",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "282",
											ignoreSize = "True",
											name = "Image_right",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/endless_plus/info/bg.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 344,
												PositionY = 378,
											},
											width = "656",
											ZOrder = "1",
										},
										{
											controlID = "Image_title2_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "fbdac7f0_2cb6_4294_b80a_528cf5edb6b6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "39",
											ignoreSize = "True",
											name = "Image_title2",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/endless_plus/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 114,
												PositionY = 539,
											},
											width = "210",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_fubenEndlessPlusView_2_Image_title2_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
													UUID = "b11473d8_c900_4185_8d64_b1e76482ff38",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "27",
													ignoreSize = "True",
													name = "Label_fubenEndlessPlusView_2",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "赛季结束时间：",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -8,
													},
													width = "155",
													ZOrder = "1",
												},
												{
													controlID = "Label_end_time_Image_title2_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
													UUID = "f668a665_614d_4d23_a7d6_88f3b27ff151",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "27",
													ignoreSize = "True",
													name = "Label_end_time",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "2020",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 87,
													},
													width = "55",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Label_floor_desc_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "d0acdc41_4ba5_4293_93b9_5af92182597a",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "1",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "180",
											ignoreSize = "False",
											name = "Label_floor_desc",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "关卡描述五十个字描述关",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 39,
												PositionY = 458,
											},
											width = "250",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_reward_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "2398a18f_c0b1_4c77_8362_6fffd30622e7",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "2",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "False",
											innerHeight = "100",
											innerWidth = "374",
											name = "ScrollView_reward",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 23,
												PositionY = 85,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "374",
											ZOrder = "1",
										},
										{
											controlID = "Label_fubenEndlessPlusView_1_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "bdfc32ac_5779_4122_8da9_cb1f940b8a3f",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_fubenEndlessPlusView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "试炼说明",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 35,
												PositionY = 483,
											},
											width = "90",
											ZOrder = "1",
										},
										{
											controlID = "Image_fubenEndlessPlusView_1_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "403f9f73_d93b_4c00_b9f0_534681720b28",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "47",
											ignoreSize = "True",
											name = "Image_fubenEndlessPlusView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/endless_plus/info/002.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 231,
												PositionY = 210,
											},
											width = "425",
											ZOrder = "1",
										},
										{
											controlID = "Label_fubenEndlessPlusView_2_Panel_right_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "60b076b0_f527_4837_9273_0ce8885797f2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_fubenEndlessPlusView_2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "奖励",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 57,
												PositionY = 207,
											},
											width = "47",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "ScrollView_level_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "4562621f_d09d_4c8b_b350_f7a7b10f99b0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "420",
									ignoreSize = "False",
									innerHeight = "420",
									innerWidth = "448",
									name = "ScrollView_level",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 107,
										PositionY = -225,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "448",
									ZOrder = "1",
								},
								{
									controlID = "Button_store_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "8c876418_6a3a_4803_95e5_fae0318a6430",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "58",
									ignoreSize = "True",
									name = "Button_store",
									normal = "ui/common/button_big_blue_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 180,
										PositionY = -271,
									},
									UItype = "Button",
									width = "134",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_btn_Button_store_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "c35298ea_3a3f_4cd6_8c55_6195c737fd07",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_btn",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "商店",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "43",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_fight_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "dcfa0728_ce71_4f50_a59e_54f6eb254aa2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "58",
									ignoreSize = "True",
									name = "Button_fight",
									normal = "ui/common/button_big_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 484,
										PositionY = -271,
									},
									UItype = "Button",
									width = "134",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_btn_Button_fight_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "787b239e_1208_45e9_ba94_7e666e84b339",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_btn",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "备  战",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "68",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_title1_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "85004ab0_23ba_49e3_95f1_e63eb9eb1f1f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "39",
									ignoreSize = "True",
									name = "Image_title1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 219,
										PositionY = 220,
									},
									width = "210",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_fubenEndlessPlusView_1_Image_title1_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "8a27e8ff_c93d_4745_86fd_93db914ef98e",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_fubenEndlessPlusView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "琴里的训练计划",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -90,
												PositionY = -2,
											},
											width = "170",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_task_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "5c8a16a0_3871_452e_9f30_acbb0cd04bb2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "58",
									ignoreSize = "True",
									name = "Button_task",
									normal = "ui/common/button_big_blue_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 332,
										PositionY = -271,
									},
									UItype = "Button",
									width = "134",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_btn_Button_task_Image_bg_Panel_root_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "4b21a4df_8d3a_4c19_ab4d_097a26f9be14",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_btn",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "成  就",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "69",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
					UUID = "0dc82a28_23bc_451e_babb_f9ad18673fe7",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = -363,
						TopPosition = 762,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_floor_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
							UUID = "6d2a4e48_83bf_4d65_9122_5f5ba9cb4c5d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "82",
							ignoreSize = "False",
							name = "Panel_floor_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -16,
								PositionY = 239,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "448",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_select_Panel_floor_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "17f0eca2_9889_46d2_9b18_8e229dc1567f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "82",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/info/004.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "448",
									ZOrder = "1",
								},
								{
									controlID = "Image_finish_Panel_floor_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "1187b8b7_42f3_4a62_a21f_fe40110f2d58",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "82",
									ignoreSize = "True",
									name = "Image_finish",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/info/003.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "422",
									ZOrder = "1",
								},
								{
									controlID = "Image_lock_Panel_floor_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "108eda73_ea5d_4c11_9890_0e6542bfc287",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "82",
									ignoreSize = "True",
									name = "Image_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/info/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "422",
									ZOrder = "1",
								},
								{
									controlID = "Label_name_Panel_floor_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "e39f74d2_3413_4e63_b53c_f9a57714b3b5",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#00FFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "TextLable",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -71,
										PositionY = -1,
									},
									width = "80",
									ZOrder = "1",
								},
								{
									controlID = "Label_tip_Panel_floor_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "43bf1dd0_d113_4653_97dc_ebb65a51e496",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#00FFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_tip",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "特训计划",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -194,
										PositionY = -1,
									},
									width = "83",
									ZOrder = "1",
								},
								{
									controlID = "Label_state_tip_Panel_floor_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "b2c083ea_6c37_4775_a958_669968dc8697",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#00FFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_state_tip",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "已解锁",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 119,
										PositionY = -1,
									},
									width = "63",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
							UUID = "5c5082ad_0781_4681_b6f4_96210386e290",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "1",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "125",
							ignoreSize = "False",
							name = "Panel_level_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 15,
								PositionY = -214,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "362",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_fubenEndlessPlusView_1_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "ffc13380_e70b_4d24_9143_d4edfb435e60",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "Image_fubenEndlessPlusView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/004.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -60,
									},
									width = "362",
									ZOrder = "1",
								},
								{
									controlID = "Label_level_name_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "71cf8482_d7f4_4858_999e_0a89c471c9f7",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF43527B",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_level_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "TextLable",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -172,
										PositionY = -16,
									},
									width = "135",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_monster_Panel_level_item_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "8ab298b6_6948_4200_b223_42e37aa465a2",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "2",
									dstBlendFunc = "771",
									height = "92",
									ignoreSize = "False",
									innerHeight = "92",
									innerWidth = "350",
									name = "ScrollView_monster",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -175,
										PositionY = -117,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "350",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_bossItem_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
							UUID = "03290d00_3b50_4d7a_a9c1_90a62492e670",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FF008000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "92",
							ignoreSize = "False",
							name = "Panel_bossItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -364,
								PositionY = -221,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "110",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_mask_Panel_bossItem_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "e08f4dce_8e4c_4ce0_8c60_74fb21b1dd80",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "92",
									ignoreSize = "False",
									name = "Panel_mask",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -24,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "156",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_boss_Panel_mask_Panel_bossItem_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
											UUID = "4fe6ef45_528f_4832_8bcc_35b63dfe8e42",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "92",
											ignoreSize = "True",
											name = "Image_boss",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/hero/battle/boss_fire.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "156",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_rewardItem_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
							UUID = "9e03bb40_8da8_45a9_b996_4dee822246cb",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "70",
							ignoreSize = "False",
							name = "Panel_rewardItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 12,
								PositionY = -61,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "70",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_item_Panel_rewardItem_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "b51f54c2_2925_479a_9bea_add63be049d7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "66",
									ignoreSize = "False",
									name = "Image_item",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/frame_blue.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "66",
									ZOrder = "1",
								},
								{
									controlID = "Image_geted_Panel_rewardItem_Panel_prefab_Panel-fubenEndlessPlusView_Layer1_fuben_Game",
									UUID = "cabc9e14_9dcf_4177_ae06_65fde025046a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "True",
									name = "Image_geted",
									scaleX = "0.7",
									scaleY = "0.7",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/endless_plus/013.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "79",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/onlineteam/BG.png",
			"ui/fuben/endless_plus/主界面.png",
			"ui/fuben/endless_plus/info/bg.png",
			"ui/fuben/endless_plus/001.png",
			"ui/fuben/endless_plus/info/002.png",
			"ui/common/button_big_blue_n.png",
			"ui/common/button_big_n.png",
			"ui/fuben/endless_plus/info/004.png",
			"ui/fuben/endless_plus/info/003.png",
			"ui/fuben/endless_plus/info/005.png",
			"ui/fuben/endless_plus/004.png",
			"icon/hero/battle/boss_fire.png",
			"ui/common/frame_blue.png",
			"ui/fuben/endless_plus/013.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

