return {
    [1] = {
        type = 1,
        id = 1,
        special = 0,
        condition = 1,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [2] = {
        type = 1,
        id = 2,
        special = 0,
        condition = 2,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [3] = {
        type = 1,
        id = 3,
        special = 0,
        condition = 3,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [4] = {
        type = 1,
        id = 4,
        special = 0,
        condition = 4,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [5] = {
        type = 1,
        id = 5,
        special = 1,
        condition = 5,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [6] = {
        type = 1,
        id = 6,
        special = 0,
        condition = 6,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [7] = {
        type = 1,
        id = 7,
        special = 0,
        condition = 7,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [8] = {
        type = 1,
        id = 8,
        special = 0,
        condition = 8,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [9] = {
        type = 1,
        id = 9,
        special = 0,
        condition = 9,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599602,
                [2] = 2,
            },
        },
    },
    [10] = {
        type = 1,
        id = 10,
        special = 1,
        condition = 10,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
        },
    },
    [11] = {
        type = 1,
        id = 11,
        special = 0,
        condition = 11,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [12] = {
        type = 1,
        id = 12,
        special = 0,
        condition = 12,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [13] = {
        type = 1,
        id = 13,
        special = 0,
        condition = 13,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [14] = {
        type = 1,
        id = 14,
        special = 0,
        condition = 14,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [15] = {
        type = 1,
        id = 15,
        special = 1,
        condition = 15,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [16] = {
        type = 1,
        id = 16,
        special = 0,
        condition = 16,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [17] = {
        type = 1,
        id = 17,
        special = 0,
        condition = 17,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [18] = {
        type = 1,
        id = 18,
        special = 0,
        condition = 18,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [19] = {
        type = 1,
        id = 19,
        special = 0,
        condition = 19,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599603,
                [2] = 1,
            },
        },
    },
    [20] = {
        type = 1,
        id = 20,
        special = 1,
        condition = 20,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
        },
    },
    [21] = {
        type = 1,
        id = 21,
        special = 0,
        condition = 21,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [22] = {
        type = 1,
        id = 22,
        special = 0,
        condition = 22,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [23] = {
        type = 1,
        id = 23,
        special = 0,
        condition = 23,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [24] = {
        type = 1,
        id = 24,
        special = 0,
        condition = 24,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [25] = {
        type = 1,
        id = 25,
        special = 1,
        condition = 25,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [26] = {
        type = 1,
        id = 26,
        special = 0,
        condition = 26,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [27] = {
        type = 1,
        id = 27,
        special = 0,
        condition = 27,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [28] = {
        type = 1,
        id = 28,
        special = 0,
        condition = 28,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [29] = {
        type = 1,
        id = 29,
        special = 0,
        condition = 29,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599603,
                [2] = 1,
            },
        },
    },
    [30] = {
        type = 1,
        id = 30,
        special = 1,
        condition = 30,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 410114,
                [2] = 1,
            },
        },
    },
    [31] = {
        type = 2,
        id = 31,
        special = 0,
        condition = 1,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599604,
                [2] = 1,
            },
        },
    },
    [32] = {
        type = 2,
        id = 32,
        special = 0,
        condition = 2,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 1,
            },
        },
    },
    [33] = {
        type = 2,
        id = 33,
        special = 0,
        condition = 3,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 6,
            },
        },
    },
    [34] = {
        type = 2,
        id = 34,
        special = 0,
        condition = 4,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 6,
            },
        },
    },
    [35] = {
        type = 2,
        id = 35,
        special = 1,
        condition = 5,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [36] = {
        type = 2,
        id = 36,
        special = 0,
        condition = 6,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520064,
                [2] = 2,
            },
        },
    },
    [37] = {
        type = 2,
        id = 37,
        special = 0,
        condition = 7,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570031,
                [2] = 3,
            },
        },
    },
    [38] = {
        type = 2,
        id = 38,
        special = 0,
        condition = 8,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 501032,
                [2] = 100,
            },
        },
    },
    [39] = {
        type = 2,
        id = 39,
        special = 0,
        condition = 9,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520023,
                [2] = 2,
            },
        },
    },
    [40] = {
        type = 2,
        id = 40,
        special = 1,
        condition = 10,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [41] = {
        type = 2,
        id = 41,
        special = 0,
        condition = 11,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510242,
                [2] = 3,
            },
        },
    },
    [42] = {
        type = 2,
        id = 42,
        special = 0,
        condition = 12,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599503,
                [2] = 1,
            },
        },
    },
    [43] = {
        type = 2,
        id = 43,
        special = 0,
        condition = 13,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 7,
            },
        },
    },
    [44] = {
        type = 2,
        id = 44,
        special = 0,
        condition = 14,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 7,
            },
        },
    },
    [45] = {
        type = 2,
        id = 45,
        special = 1,
        condition = 15,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 599605,
                [2] = 1,
            },
        },
    },
    [46] = {
        type = 2,
        id = 46,
        special = 0,
        condition = 16,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 2,
            },
        },
    },
    [47] = {
        type = 2,
        id = 47,
        special = 0,
        condition = 17,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520063,
                [2] = 4,
            },
        },
    },
    [48] = {
        type = 2,
        id = 48,
        special = 0,
        condition = 18,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570031,
                [2] = 4,
            },
        },
    },
    [49] = {
        type = 2,
        id = 49,
        special = 0,
        condition = 19,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520023,
                [2] = 3,
            },
        },
    },
    [50] = {
        type = 2,
        id = 50,
        special = 1,
        condition = 20,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [51] = {
        type = 2,
        id = 51,
        special = 0,
        condition = 21,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510242,
                [2] = 3,
            },
        },
    },
    [52] = {
        type = 2,
        id = 52,
        special = 0,
        condition = 22,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570002,
                [2] = 20,
            },
        },
    },
    [53] = {
        type = 2,
        id = 53,
        special = 0,
        condition = 23,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 8,
            },
        },
    },
    [54] = {
        type = 2,
        id = 54,
        special = 0,
        condition = 24,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 8,
            },
        },
    },
    [55] = {
        type = 2,
        id = 55,
        special = 1,
        condition = 25,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [56] = {
        type = 2,
        id = 56,
        special = 0,
        condition = 26,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 501032,
                [2] = 200,
            },
        },
    },
    [57] = {
        type = 2,
        id = 57,
        special = 0,
        condition = 27,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 3,
            },
        },
    },
    [58] = {
        type = 2,
        id = 58,
        special = 0,
        condition = 28,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 9,
            },
        },
    },
    [59] = {
        type = 2,
        id = 59,
        special = 0,
        condition = 29,
        nameTextId = 0,
        returnnewbleId = 130023,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 9,
            },
        },
    },
    [60] = {
        type = 2,
        id = 60,
        special = 1,
        condition = 30,
        nameTextId = 63928,
        returnnewbleId = 130023,
        preview = 1,
        icon = "ui\\task\\01\\02\\11.png",
        reward = {
            [1] = {
                [1] = 410113,
                [2] = 1,
            },
        },
    },
    [61] = {
        type = 1,
        id = 61,
        special = 0,
        condition = 1,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [62] = {
        type = 1,
        id = 62,
        special = 0,
        condition = 2,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [63] = {
        type = 1,
        id = 63,
        special = 0,
        condition = 3,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [64] = {
        type = 1,
        id = 64,
        special = 0,
        condition = 4,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [65] = {
        type = 1,
        id = 65,
        special = 1,
        condition = 5,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [66] = {
        type = 1,
        id = 66,
        special = 0,
        condition = 6,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [67] = {
        type = 1,
        id = 67,
        special = 0,
        condition = 7,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [68] = {
        type = 1,
        id = 68,
        special = 0,
        condition = 8,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [69] = {
        type = 1,
        id = 69,
        special = 0,
        condition = 9,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599602,
                [2] = 2,
            },
        },
    },
    [70] = {
        type = 1,
        id = 70,
        special = 1,
        condition = 10,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
        },
    },
    [71] = {
        type = 1,
        id = 71,
        special = 0,
        condition = 11,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [72] = {
        type = 1,
        id = 72,
        special = 0,
        condition = 12,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [73] = {
        type = 1,
        id = 73,
        special = 0,
        condition = 13,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [74] = {
        type = 1,
        id = 74,
        special = 0,
        condition = 14,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [75] = {
        type = 1,
        id = 75,
        special = 1,
        condition = 15,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [76] = {
        type = 1,
        id = 76,
        special = 0,
        condition = 16,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [77] = {
        type = 1,
        id = 77,
        special = 0,
        condition = 17,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [78] = {
        type = 1,
        id = 78,
        special = 0,
        condition = 18,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [79] = {
        type = 1,
        id = 79,
        special = 0,
        condition = 19,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599603,
                [2] = 1,
            },
        },
    },
    [80] = {
        type = 1,
        id = 80,
        special = 1,
        condition = 20,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
        },
    },
    [81] = {
        type = 1,
        id = 81,
        special = 0,
        condition = 21,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [82] = {
        type = 1,
        id = 82,
        special = 0,
        condition = 22,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [83] = {
        type = 1,
        id = 83,
        special = 0,
        condition = 23,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [84] = {
        type = 1,
        id = 84,
        special = 0,
        condition = 24,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [85] = {
        type = 1,
        id = 85,
        special = 1,
        condition = 25,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [86] = {
        type = 1,
        id = 86,
        special = 0,
        condition = 26,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [87] = {
        type = 1,
        id = 87,
        special = 0,
        condition = 27,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [88] = {
        type = 1,
        id = 88,
        special = 0,
        condition = 28,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [89] = {
        type = 1,
        id = 89,
        special = 0,
        condition = 29,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599603,
                [2] = 1,
            },
        },
    },
    [90] = {
        type = 1,
        id = 90,
        special = 1,
        condition = 30,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 410220,
                [2] = 1,
            },
        },
    },
    [91] = {
        type = 2,
        id = 91,
        special = 0,
        condition = 1,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599604,
                [2] = 1,
            },
        },
    },
    [92] = {
        type = 2,
        id = 92,
        special = 0,
        condition = 2,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 1,
            },
        },
    },
    [93] = {
        type = 2,
        id = 93,
        special = 0,
        condition = 3,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 6,
            },
        },
    },
    [94] = {
        type = 2,
        id = 94,
        special = 0,
        condition = 4,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 6,
            },
        },
    },
    [95] = {
        type = 2,
        id = 95,
        special = 1,
        condition = 5,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [96] = {
        type = 2,
        id = 96,
        special = 0,
        condition = 6,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520064,
                [2] = 2,
            },
        },
    },
    [97] = {
        type = 2,
        id = 97,
        special = 0,
        condition = 7,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570031,
                [2] = 3,
            },
        },
    },
    [98] = {
        type = 2,
        id = 98,
        special = 0,
        condition = 8,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 501032,
                [2] = 100,
            },
        },
    },
    [99] = {
        type = 2,
        id = 99,
        special = 0,
        condition = 9,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520023,
                [2] = 2,
            },
        },
    },
    [100] = {
        type = 2,
        id = 100,
        special = 1,
        condition = 10,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [101] = {
        type = 2,
        id = 101,
        special = 0,
        condition = 11,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510242,
                [2] = 3,
            },
        },
    },
    [102] = {
        type = 2,
        id = 102,
        special = 0,
        condition = 12,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599503,
                [2] = 1,
            },
        },
    },
    [103] = {
        type = 2,
        id = 103,
        special = 0,
        condition = 13,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 7,
            },
        },
    },
    [104] = {
        type = 2,
        id = 104,
        special = 0,
        condition = 14,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 7,
            },
        },
    },
    [105] = {
        type = 2,
        id = 105,
        special = 1,
        condition = 15,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 599605,
                [2] = 1,
            },
        },
    },
    [106] = {
        type = 2,
        id = 106,
        special = 0,
        condition = 16,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 2,
            },
        },
    },
    [107] = {
        type = 2,
        id = 107,
        special = 0,
        condition = 17,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520063,
                [2] = 4,
            },
        },
    },
    [108] = {
        type = 2,
        id = 108,
        special = 0,
        condition = 18,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570031,
                [2] = 4,
            },
        },
    },
    [109] = {
        type = 2,
        id = 109,
        special = 0,
        condition = 19,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520023,
                [2] = 3,
            },
        },
    },
    [110] = {
        type = 2,
        id = 110,
        special = 1,
        condition = 20,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [111] = {
        type = 2,
        id = 111,
        special = 0,
        condition = 21,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510242,
                [2] = 3,
            },
        },
    },
    [112] = {
        type = 2,
        id = 112,
        special = 0,
        condition = 22,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570002,
                [2] = 20,
            },
        },
    },
    [113] = {
        type = 2,
        id = 113,
        special = 0,
        condition = 23,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 8,
            },
        },
    },
    [114] = {
        type = 2,
        id = 114,
        special = 0,
        condition = 24,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 8,
            },
        },
    },
    [115] = {
        type = 2,
        id = 115,
        special = 1,
        condition = 25,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [116] = {
        type = 2,
        id = 116,
        special = 0,
        condition = 26,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 501032,
                [2] = 200,
            },
        },
    },
    [117] = {
        type = 2,
        id = 117,
        special = 0,
        condition = 27,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 3,
            },
        },
    },
    [118] = {
        type = 2,
        id = 118,
        special = 0,
        condition = 28,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 9,
            },
        },
    },
    [119] = {
        type = 2,
        id = 119,
        special = 0,
        condition = 29,
        nameTextId = 0,
        returnnewbleId = 130024,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 9,
            },
        },
    },
    [120] = {
        type = 2,
        id = 120,
        special = 1,
        condition = 30,
        nameTextId = 63929,
        returnnewbleId = 130024,
        preview = 1,
        icon = "ui\\task\\01\\02\\22.png",
        reward = {
            [1] = {
                [1] = 410219,
                [2] = 1,
            },
        },
    },
    [121] = {
        type = 1,
        id = 121,
        special = 0,
        condition = 1,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [122] = {
        type = 1,
        id = 122,
        special = 0,
        condition = 2,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [123] = {
        type = 1,
        id = 123,
        special = 0,
        condition = 3,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [124] = {
        type = 1,
        id = 124,
        special = 0,
        condition = 4,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [125] = {
        type = 1,
        id = 125,
        special = 1,
        condition = 5,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [126] = {
        type = 1,
        id = 126,
        special = 0,
        condition = 6,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [127] = {
        type = 1,
        id = 127,
        special = 0,
        condition = 7,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [128] = {
        type = 1,
        id = 128,
        special = 0,
        condition = 8,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [129] = {
        type = 1,
        id = 129,
        special = 0,
        condition = 9,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599602,
                [2] = 2,
            },
        },
    },
    [130] = {
        type = 1,
        id = 130,
        special = 1,
        condition = 10,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
        },
    },
    [131] = {
        type = 1,
        id = 131,
        special = 0,
        condition = 11,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [132] = {
        type = 1,
        id = 132,
        special = 0,
        condition = 12,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [133] = {
        type = 1,
        id = 133,
        special = 0,
        condition = 13,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [134] = {
        type = 1,
        id = 134,
        special = 0,
        condition = 14,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [135] = {
        type = 1,
        id = 135,
        special = 1,
        condition = 15,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [136] = {
        type = 1,
        id = 136,
        special = 0,
        condition = 16,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [137] = {
        type = 1,
        id = 137,
        special = 0,
        condition = 17,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [138] = {
        type = 1,
        id = 138,
        special = 0,
        condition = 18,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [139] = {
        type = 1,
        id = 139,
        special = 0,
        condition = 19,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599603,
                [2] = 1,
            },
        },
    },
    [140] = {
        type = 1,
        id = 140,
        special = 1,
        condition = 20,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
        },
    },
    [141] = {
        type = 1,
        id = 141,
        special = 0,
        condition = 21,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520006,
                [2] = 1,
            },
        },
    },
    [142] = {
        type = 1,
        id = 142,
        special = 0,
        condition = 22,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [143] = {
        type = 1,
        id = 143,
        special = 0,
        condition = 23,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520021,
                [2] = 2,
            },
        },
    },
    [144] = {
        type = 1,
        id = 144,
        special = 0,
        condition = 24,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [145] = {
        type = 1,
        id = 145,
        special = 1,
        condition = 25,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 3,
            },
        },
    },
    [146] = {
        type = 1,
        id = 146,
        special = 0,
        condition = 26,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [147] = {
        type = 1,
        id = 147,
        special = 0,
        condition = 27,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 3,
            },
        },
    },
    [148] = {
        type = 1,
        id = 148,
        special = 0,
        condition = 28,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
        },
    },
    [149] = {
        type = 1,
        id = 149,
        special = 0,
        condition = 29,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599603,
                [2] = 1,
            },
        },
    },
    [150] = {
        type = 1,
        id = 150,
        special = 1,
        condition = 30,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 410312,
                [2] = 1,
            },
        },
    },
    [151] = {
        type = 2,
        id = 151,
        special = 0,
        condition = 1,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599604,
                [2] = 1,
            },
        },
    },
    [152] = {
        type = 2,
        id = 152,
        special = 0,
        condition = 2,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 1,
            },
        },
    },
    [153] = {
        type = 2,
        id = 153,
        special = 0,
        condition = 3,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 6,
            },
        },
    },
    [154] = {
        type = 2,
        id = 154,
        special = 0,
        condition = 4,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 6,
            },
        },
    },
    [155] = {
        type = 2,
        id = 155,
        special = 1,
        condition = 5,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [156] = {
        type = 2,
        id = 156,
        special = 0,
        condition = 6,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520064,
                [2] = 2,
            },
        },
    },
    [157] = {
        type = 2,
        id = 157,
        special = 0,
        condition = 7,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570031,
                [2] = 3,
            },
        },
    },
    [158] = {
        type = 2,
        id = 158,
        special = 0,
        condition = 8,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 501032,
                [2] = 100,
            },
        },
    },
    [159] = {
        type = 2,
        id = 159,
        special = 0,
        condition = 9,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520023,
                [2] = 2,
            },
        },
    },
    [160] = {
        type = 2,
        id = 160,
        special = 1,
        condition = 10,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [161] = {
        type = 2,
        id = 161,
        special = 0,
        condition = 11,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510242,
                [2] = 3,
            },
        },
    },
    [162] = {
        type = 2,
        id = 162,
        special = 0,
        condition = 12,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 599503,
                [2] = 1,
            },
        },
    },
    [163] = {
        type = 2,
        id = 163,
        special = 0,
        condition = 13,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 7,
            },
        },
    },
    [164] = {
        type = 2,
        id = 164,
        special = 0,
        condition = 14,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 7,
            },
        },
    },
    [165] = {
        type = 2,
        id = 165,
        special = 1,
        condition = 15,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 599605,
                [2] = 1,
            },
        },
    },
    [166] = {
        type = 2,
        id = 166,
        special = 0,
        condition = 16,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 2,
            },
        },
    },
    [167] = {
        type = 2,
        id = 167,
        special = 0,
        condition = 17,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520063,
                [2] = 4,
            },
        },
    },
    [168] = {
        type = 2,
        id = 168,
        special = 0,
        condition = 18,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570031,
                [2] = 4,
            },
        },
    },
    [169] = {
        type = 2,
        id = 169,
        special = 0,
        condition = 19,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520023,
                [2] = 3,
            },
        },
    },
    [170] = {
        type = 2,
        id = 170,
        special = 1,
        condition = 20,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [171] = {
        type = 2,
        id = 171,
        special = 0,
        condition = 21,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510242,
                [2] = 3,
            },
        },
    },
    [172] = {
        type = 2,
        id = 172,
        special = 0,
        condition = 22,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 570002,
                [2] = 20,
            },
        },
    },
    [173] = {
        type = 2,
        id = 173,
        special = 0,
        condition = 23,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 8,
            },
        },
    },
    [174] = {
        type = 2,
        id = 174,
        special = 0,
        condition = 24,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 8,
            },
        },
    },
    [175] = {
        type = 2,
        id = 175,
        special = 1,
        condition = 25,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 1,
        icon = "",
        reward = {
            [1] = {
                [1] = 570033,
                [2] = 1,
            },
        },
    },
    [176] = {
        type = 2,
        id = 176,
        special = 0,
        condition = 26,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 501032,
                [2] = 200,
            },
        },
    },
    [177] = {
        type = 2,
        id = 177,
        special = 0,
        condition = 27,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 520065,
                [2] = 3,
            },
        },
    },
    [178] = {
        type = 2,
        id = 178,
        special = 0,
        condition = 28,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510105,
                [2] = 9,
            },
        },
    },
    [179] = {
        type = 2,
        id = 179,
        special = 0,
        condition = 29,
        nameTextId = 0,
        returnnewbleId = 130025,
        preview = 0,
        icon = "",
        reward = {
            [1] = {
                [1] = 510155,
                [2] = 9,
            },
        },
    },
    [180] = {
        type = 2,
        id = 180,
        special = 1,
        condition = 30,
        nameTextId = 63930,
        returnnewbleId = 130025,
        preview = 1,
        icon = "ui\\task\\01\\02\\31.png",
        reward = {
            [1] = {
                [1] = 410311,
                [2] = 1,
            },
        },
    },
}