return {
    [1] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 1,
        interType = 3,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/018.png",
        effectPath = "",
    },
    [2] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 2,
        interType = 4,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/leave.png",
        effectPath = "",
    },
    [10] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 1,
            },
            jumpInterface = 301,
        },
        asyn = false,
        id = 10,
        interType = 1,
        effectAction = "animation",
        actionButton = "ui/activity/znq_yly/mainUi/017.png",
        effectPath = "effect/world/UI_botton/UI_anniu",
    },
    [11] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 1,
            },
            jumpInterface = 307,
        },
        asyn = false,
        id = 11,
        interType = 1,
        effectAction = "animation",
        actionButton = "ui/activity/znq_yly/mainUi/017.png",
        effectPath = "effect/world/UI_botton/UI_anniu",
    },
    [12] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 1,
            },
            jumpInterface = 305,
        },
        asyn = false,
        id = 12,
        interType = 1,
        effectAction = "animation",
        actionButton = "ui/activity/znq_yly/mainUi/017.png",
        effectPath = "effect/world/UI_botton/UI_anniu",
    },
    [13] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 7,
                [2] = 120016,
            },
            jumpInterface = 308,
        },
        asyn = false,
        id = 13,
        interType = 1,
        effectAction = "animation",
        actionButton = "ui/activity/znq_yly/mainUi/017.png",
        effectPath = "effect/world/UI_botton/UI_anniu",
    },
    [14] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 1,
            },
            jumpInterface = 303,
        },
        asyn = false,
        id = 14,
        interType = 1,
        effectAction = "animation",
        actionButton = "ui/activity/znq_yly/mainUi/017.png",
        effectPath = "effect/world/UI_botton/UI_anniu",
    },
    [15] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 1,
            },
            jumpInterface = 304,
        },
        asyn = false,
        id = 15,
        interType = 1,
        effectAction = "animation",
        actionButton = "ui/activity/znq_yly/mainUi/017.png",
        effectPath = "effect/world/UI_botton/UI_anniu",
    },
    [16] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 1,
            },
            jumpInterface = 306,
        },
        asyn = false,
        id = 16,
        interType = 1,
        effectAction = "animation",
        actionButton = "ui/activity/znq_yly/mainUi/017.png",
        effectPath = "effect/world/UI_botton/UI_anniu",
    },
    [83] = {
        isAuto = true,
        autoDelayTime = 30,
        interTypeParma = {
            actionId = 31002,
        },
        asyn = true,
        id = 83,
        interType = 5,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [85] = {
        isAuto = true,
        autoDelayTime = 30,
        interTypeParma = {
        },
        asyn = true,
        id = 85,
        interType = 2,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [60] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            actionCondId = 1001,
        },
        asyn = false,
        id = 60,
        interType = 6,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/highFive.png",
        effectPath = "",
    },
    [70] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            parameter = {
                [1] = 749026,
            },
            jumpInterface = 84,
        },
        asyn = false,
        id = 70,
        interType = 1,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/investigate.png",
        effectPath = "",
    },
    [20] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 20,
        interType = 2,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/021.png",
        effectPath = "",
    },
    [80] = {
        isAuto = true,
        autoDelayTime = 10,
        interTypeParma = {
            childType = 1,
            cond = {
                flag = 2,
            },
            actorCfgId = {
                [1] = 2001,
                [2] = 2002,
                [3] = 2003,
                [4] = 2004,
                [5] = 2005,
                [6] = 2006,
                [7] = 2007,
                [8] = 2008,
                [9] = 2009,
                [10] = 2010,
                [11] = 2011,
                [12] = 2012,
                [13] = 2013,
                [14] = 2014,
                [15] = 2015,
            },
            pos = {
                [1] = 624,
                [2] = 360,
            },
        },
        asyn = false,
        id = 80,
        interType = 7,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [82] = {
        isAuto = true,
        autoDelayTime = 0,
        interTypeParma = {
            pos = {
                [1] = 1329,
                [2] = 133,
            },
        },
        asyn = false,
        id = 82,
        interType = 9,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [22] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 22,
        interType = 2,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [86] = {
        isAuto = true,
        autoDelayTime = 30,
        interTypeParma = {
            actionId = 31004,
        },
        asyn = true,
        id = 86,
        interType = 5,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [23] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 23,
        interType = 2,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/019.png",
        effectPath = "",
    },
    [24] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 24,
        interType = 2,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/019.png",
        effectPath = "",
    },
    [25] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 25,
        interType = 2,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [50] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
            actionId = 21001,
        },
        asyn = false,
        id = 50,
        interType = 5,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/highFive.png",
        effectPath = "",
    },
    [88] = {
        isAuto = true,
        autoDelayTime = 30,
        interTypeParma = {
            actionId = 31006,
        },
        asyn = false,
        id = 88,
        interType = 5,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [87] = {
        isAuto = true,
        autoDelayTime = 30,
        interTypeParma = {
            actionId = 31005,
        },
        asyn = true,
        id = 87,
        interType = 5,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [84] = {
        isAuto = true,
        autoDelayTime = 30,
        interTypeParma = {
            actionId = 31003,
        },
        asyn = true,
        id = 84,
        interType = 5,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [81] = {
        isAuto = true,
        autoDelayTime = 30,
        interTypeParma = {
            removeChildType = {
                [1] = 1,
            },
        },
        asyn = false,
        id = 81,
        interType = 8,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/020.png",
        effectPath = "",
    },
    [21] = {
        isAuto = false,
        autoDelayTime = 0,
        interTypeParma = {
        },
        asyn = false,
        id = 21,
        interType = 2,
        effectAction = "",
        actionButton = "ui/activity/znq_yly/mainUi/019.png",
        effectPath = "",
    },
}