return {
    [1] = {
        synPosTime  = 0,
        cameraSlowMoveSpeed = 0,
        controlobj = 0,
        worldType = 1,
        mapResource = "",
        showObjectId = 0,
        type = 1,
        bornPos  = {
        },
        worldRoomStart = 0,
        isSingle  = false,
        syncPlayerNum = 0,
        heartBeatDeal = 0,
        whiteModel = "",
        interButtonNum = 0,
        moveSpeed = 0,
        cameraScope = 150,
        id = 1,
        modelScale = 1,
        netReconnectCount = 0,
        ableActionTypes = {
        },
        param = {
            roomNum = 200,
            roomMaxNum = 400,
            guildNum = 500,
            roomPlayer = 25,
            roomMaxplayer = 50,
            time = 10,
            guildTime = 10,
            enterTime = 20,
            bornPos = {
                [1] = {
                    [1] = 100,
                    [2] = 1200,
                },
                [2] = {
                    [1] = 100,
                    [2] = 300,
                },
            },
        },
    },
    [2] = {
        synPosTime  = 0,
        cameraSlowMoveSpeed = 0,
        controlobj = 0,
        worldType = 2,
        mapResource = "",
        showObjectId = 0,
        type = 2,
        bornPos  = {
        },
        worldRoomStart = 0,
        isSingle  = false,
        syncPlayerNum = 0,
        heartBeatDeal = 0,
        whiteModel = "",
        interButtonNum = 0,
        moveSpeed = 0,
        cameraScope = 150,
        id = 2,
        modelScale = 1,
        netReconnectCount = 0,
        ableActionTypes = {
        },
        param = {
            roomNum = 200,
            roomMaxNum = 400,
            guildNum = 500,
            roomPlayer = 25,
            roomMaxplayer = 50,
            time = 10,
            guildTime = 10,
            enterTime = 20,
            bornPos = {
                [1] = {
                    [1] = 100,
                    [2] = 1200,
                },
                [2] = {
                    [1] = 100,
                    [2] = 300,
                },
            },
        },
    },
    [3] = {
        synPosTime  = 60,
        cameraSlowMoveSpeed = 100,
        controlobj = 0,
        worldType = 1,
        mapResource = "anniversary_springFes",
        showObjectId = 0,
        type = 3,
        bornPos  = {
            [1] = {
                [1] = 917,
                [2] = 281,
            },
            [2] = {
                [1] = 1470,
                [2] = 1687,
            },
            [3] = {
                [1] = 2679,
                [2] = 811,
            },
            [4] = {
                [1] = 4908,
                [2] = 1185,
            },
            [5] = {
                [1] = 2149,
                [2] = 2028,
            },
            [6] = {
                [1] = 4527,
                [2] = 279,
            },
            [7] = {
                [1] = 4304,
                [2] = 1924,
            },
            [8] = {
                [1] = 3183,
                [2] = 1778,
            },
        },
        worldRoomStart = 2000,
        isSingle  = false,
        syncPlayerNum = 13,
        heartBeatDeal = 10000,
        whiteModel = "modle/citymodle/baseModel.png",
        interButtonNum = 5,
        moveSpeed = 285,
        cameraScope = 300,
        id = 3,
        modelScale = 0.6,
        netReconnectCount = 3,
        ableActionTypes = {
            [1] = 1,
            [2] = 2,
            [3] = 3,
            [4] = 4,
            [5] = 5,
            [6] = 6,
        },
        param = {
            roomNum = 200,
            roomMaxNum = 400,
            guildNum = 500,
            roomPlayer = 25,
            roomMaxplayer = 50,
            time = 10,
            guildTime = 10,
            enterTime = 20,
            bornPos = {
                [1] = {
                    [1] = 3065,
                    [2] = 3085,
                },
                [2] = {
                    [1] = 945,
                    [2] = 955,
                },
            },
        },
    },
    [4] = {
        synPosTime  = 60,
        cameraSlowMoveSpeed = 100,
        controlobj = 0,
        worldType = 2,
        mapResource = "anniversary_springFes",
        showObjectId = 0,
        type = 4,
        bornPos  = {
            [1] = {
                [1] = 917,
                [2] = 281,
            },
            [2] = {
                [1] = 1470,
                [2] = 1687,
            },
            [3] = {
                [1] = 2679,
                [2] = 811,
            },
            [4] = {
                [1] = 4908,
                [2] = 1185,
            },
            [5] = {
                [1] = 2149,
                [2] = 2028,
            },
            [6] = {
                [1] = 4527,
                [2] = 279,
            },
            [7] = {
                [1] = 4304,
                [2] = 1924,
            },
            [8] = {
                [1] = 3183,
                [2] = 1778,
            },
        },
        worldRoomStart = 1,
        isSingle  = false,
        syncPlayerNum = 13,
        heartBeatDeal = 10000,
        whiteModel = "modle/citymodle/baseModel.png",
        interButtonNum = 5,
        moveSpeed = 285,
        cameraScope = 300,
        id = 4,
        modelScale = 0.6,
        netReconnectCount = 3,
        ableActionTypes = {
            [1] = 1,
            [2] = 2,
            [3] = 3,
            [4] = 4,
            [5] = 5,
            [6] = 6,
        },
        param = {
            roomNum = 200,
            roomMaxNum = 400,
            guildNum = 500,
            roomPlayer = 25,
            roomMaxplayer = 50,
            time = 10,
            guildTime = 10,
            enterTime = 20,
            bornPos = {
                [1] = {
                    [1] = 3065,
                    [2] = 3085,
                },
                [2] = {
                    [1] = 945,
                    [2] = 955,
                },
            },
        },
    },
    [100003] = {
        synPosTime  = 60,
        cameraSlowMoveSpeed = 100,
        controlobj = 0,
        worldType = 1,
        mapResource = "anniversary",
        showObjectId = 301,
        type = 3,
        bornPos  = {
            [1] = {
                [1] = 1732,
                [2] = 431,
            },
            [2] = {
                [1] = 1288,
                [2] = 1209,
            },
            [3] = {
                [1] = 2615,
                [2] = 849,
            },
            [4] = {
                [1] = 3662,
                [2] = 1297,
            },
            [5] = {
                [1] = 1992,
                [2] = 1761,
            },
            [6] = {
                [1] = 4120,
                [2] = 733,
            },
            [7] = {
                [1] = 3233,
                [2] = 1479,
            },
            [8] = {
                [1] = 2678,
                [2] = 1991,
            },
            [9] = {
                [1] = 4430,
                [2] = 1699,
            },
        },
        worldRoomStart = 2000,
        isSingle  = false,
        syncPlayerNum = 13,
        heartBeatDeal = 10000,
        whiteModel = "modle/citymodle/baseModel.png",
        interButtonNum = 3,
        moveSpeed = 285,
        cameraScope = 300,
        id = 100003,
        modelScale = 0.6,
        netReconnectCount = 3,
        ableActionTypes = {
            [1] = 1,
            [2] = 2,
            [3] = 3,
            [4] = 4,
            [5] = 5,
            [6] = 6,
        },
        param = {
            roomNum = 200,
            roomMaxNum = 400,
            guildNum = 500,
            roomPlayer = 25,
            roomMaxplayer = 50,
            time = 10,
            guildTime = 10,
            enterTime = 20,
            bornPos = {
                [1] = {
                    [1] = 2567,
                    [2] = 2667,
                },
                [2] = {
                    [1] = 702,
                    [2] = 802,
                },
            },
        },
    },
    [99] = {
        synPosTime  = 60,
        cameraSlowMoveSpeed = 100,
        controlobj = 1004,
        worldType = 1,
        mapResource = "active_maoka",
        showObjectId = 0,
        type = 99,
        bornPos  = {
        },
        worldRoomStart = 0,
        isSingle  = true,
        syncPlayerNum = 13,
        heartBeatDeal = 10000,
        whiteModel = "",
        interButtonNum = 3,
        moveSpeed = 100,
        cameraScope = 150,
        id = 99,
        modelScale = 0.6,
        netReconnectCount = 3,
        ableActionTypes = {
            [1] = 1,
            [2] = 2,
            [3] = 3,
            [4] = 4,
            [5] = 5,
            [6] = 6,
        },
        param = {
        },
    },
    [100004] = {
        synPosTime  = 60,
        cameraSlowMoveSpeed = 100,
        controlobj = 0,
        worldType = 2,
        mapResource = "anniversary",
        showObjectId = 301,
        type = 4,
        bornPos  = {
            [1] = {
                [1] = 1732,
                [2] = 431,
            },
            [2] = {
                [1] = 1288,
                [2] = 1209,
            },
            [3] = {
                [1] = 2615,
                [2] = 849,
            },
            [4] = {
                [1] = 3662,
                [2] = 1297,
            },
            [5] = {
                [1] = 1992,
                [2] = 1761,
            },
            [6] = {
                [1] = 4120,
                [2] = 733,
            },
            [7] = {
                [1] = 3233,
                [2] = 1479,
            },
            [8] = {
                [1] = 2678,
                [2] = 1991,
            },
            [9] = {
                [1] = 4430,
                [2] = 1699,
            },
        },
        worldRoomStart = 1,
        isSingle  = false,
        syncPlayerNum = 13,
        heartBeatDeal = 10000,
        whiteModel = "modle/citymodle/baseModel.png",
        interButtonNum = 3,
        moveSpeed = 285,
        cameraScope = 300,
        id = 100004,
        modelScale = 0.6,
        netReconnectCount = 3,
        ableActionTypes = {
            [1] = 1,
            [2] = 2,
            [3] = 3,
            [4] = 4,
            [5] = 5,
            [6] = 6,
        },
        param = {
            roomNum = 200,
            roomMaxNum = 400,
            guildNum = 500,
            roomPlayer = 25,
            roomMaxplayer = 50,
            time = 10,
            guildTime = 10,
            enterTime = 20,
            bornPos = {
                [1] = {
                    [1] = 2567,
                    [2] = 2667,
                },
                [2] = {
                    [1] = 702,
                    [2] = 802,
                },
            },
        },
    },
}