return {
    [106] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play",
        audioId = 705,
        objectAction = "",
        dirFollowObj = false,
        id = 106,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/world/chrMotion/emotionBubble_1006",
        audioRange = 400,
    },
    [910001] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "idle",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 910001,
        audioRate = 0,
        hideShadow = false,
        offSet = {
            y = 30,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = true,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/SDeffectEquip/910000/SDeffect_910000",
        audioRange = 0,
    },
    [12106] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play2",
        audioId = 0,
        objectAction = "play",
        dirFollowObj = false,
        id = 12106,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = true,
        objectActIsLoop = true,
        motionRecourse_1 = "citymap/world/object/stage_effect/crystal",
        audioRange = 0,
    },
    [3004] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "happy",
        dirFollowObj = false,
        id = 3004,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [12107] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "animation",
        dirFollowObj = false,
        id = 12107,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10501] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 10501,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [12108] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "idle1",
        dirFollowObj = false,
        id = 12108,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [21001] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 21001,
        audioRate = 0,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [21002] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "qiqiu_LV1",
        audioId = 8111,
        objectAction = "",
        dirFollowObj = false,
        id = 21002,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/2zn_qiqiu/2zn_qiqiu",
        audioRange = 300,
    },
    [21003] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "qiqiu_LV2",
        audioId = 8111,
        objectAction = "",
        dirFollowObj = false,
        id = 21003,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/2zn_qiqiu/2zn_qiqiu",
        audioRange = 300,
    },
    [10000] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "idle",
        dirFollowObj = false,
        id = 10000,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [21005] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "qiqiu_LV4",
        audioId = 8111,
        objectAction = "",
        dirFollowObj = false,
        id = 21005,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/2zn_qiqiu/2zn_qiqiu",
        audioRange = 300,
    },
    [10001] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "born",
        dirFollowObj = false,
        id = 10001,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10002] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "inter",
        dirFollowObj = false,
        id = 10002,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10601] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 10601,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [910002201] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "happy",
        audioId = 8102,
        objectAction = "happy",
        dirFollowObj = true,
        id = 910002201,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 140,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/SDeffectEquip/910000/SDeffect_910000",
        audioRange = 500,
    },
    [31008] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 6000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "disappear",
        dirFollowObj = false,
        id = 31008,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [104] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play",
        audioId = 8112,
        objectAction = "",
        dirFollowObj = false,
        id = 104,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/world/chrMotion/emotionBubble_1004",
        audioRange = 400,
    },
    [31006] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 4,
        aiDelayTime = 10000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "tiaoyue",
        dirFollowObj = false,
        id = 31006,
        audioRate = 0,
        hideShadow = true,
        offSet = {
        },
        beStand = true,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10101] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "idle",
        dirFollowObj = false,
        id = 10101,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [31005] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 5000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "doumaobang2",
        dirFollowObj = false,
        id = 31005,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = true,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10102] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "idle1",
        dirFollowObj = false,
        id = 10102,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10701] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 10701,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10103] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "idle2",
        dirFollowObj = false,
        id = 10103,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [910001201] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "happy",
        audioId = 8101,
        objectAction = "happy",
        dirFollowObj = true,
        id = 910001201,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 140,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/SDeffectEquip/910001/SDeffect_910001",
        audioRange = 500,
    },
    [31004] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 8000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "siyaohaozi",
        dirFollowObj = false,
        id = 31004,
        audioRate = 0,
        hideShadow = true,
        offSet = {
        },
        beStand = true,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [202] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "surprise",
        dirFollowObj = false,
        id = 202,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [31002] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 3000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "zhamao",
        dirFollowObj = false,
        id = 31002,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = true,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [105] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play",
        audioId = 705,
        objectAction = "",
        dirFollowObj = false,
        id = 105,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/world/chrMotion/emotionBubble_1005",
        audioRange = 400,
    },
    [3005] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "idle",
        dirFollowObj = false,
        id = 3005,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [10201] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 10201,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [21006] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "qiqiu_LV5",
        audioId = 8111,
        objectAction = "",
        dirFollowObj = false,
        id = 21006,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/2zn_qiqiu/2zn_qiqiu",
        audioRange = 300,
    },
    [21004] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "qiqiu_LV3",
        audioId = 8111,
        objectAction = "",
        dirFollowObj = false,
        id = 21004,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/2zn_qiqiu/2zn_qiqiu",
        audioRange = 300,
    },
    [10401] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 10401,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [13101] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "inter",
        dirFollowObj = false,
        id = 13101,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [12105] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play1",
        audioId = 0,
        objectAction = "play",
        dirFollowObj = false,
        id = 12105,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = true,
        objectActIsLoop = true,
        motionRecourse_1 = "citymap/world/object/stage_effect/crystal",
        audioRange = 0,
    },
    [13102] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 8103,
        objectAction = "open",
        dirFollowObj = false,
        id = 13102,
        audioRate = 60,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 500,
    },
    [3001] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "rest",
        dirFollowObj = false,
        id = 3001,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [101] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play",
        audioId = 705,
        objectAction = "",
        dirFollowObj = false,
        id = 101,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/world/chrMotion/emotionBubble_1001",
        audioRange = 400,
    },
    [12103] = {
        playCond = {
        },
        audioLoop = true,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 8110,
        objectAction = "play",
        dirFollowObj = false,
        id = 12103,
        audioRate = 60,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 500,
    },
    [201] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play",
        audioId = 0,
        objectAction = "happy",
        dirFollowObj = true,
        id = 201,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "all",
        audioRange = 0,
    },
    [10301] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 10301,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [102] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play",
        audioId = 705,
        objectAction = "",
        dirFollowObj = false,
        id = 102,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/world/chrMotion/emotionBubble_1002",
        audioRange = 400,
    },
    [12102] = {
        playCond = {
            playMix = 2,
        },
        audioLoop = true,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 8109,
        objectAction = "play",
        dirFollowObj = false,
        id = 12102,
        audioRate = 60,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 500,
    },
    [203] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "hungry",
        dirFollowObj = false,
        id = 203,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [3002] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "sit",
        dirFollowObj = false,
        id = 3002,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [103] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "play",
        audioId = 8113,
        objectAction = "",
        dirFollowObj = false,
        id = 103,
        audioRate = 60,
        hideShadow = false,
        offSet = {
            y = 130,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/world/chrMotion/emotionBubble_1003",
        audioRange = 400,
    },
    [12101] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "play",
        dirFollowObj = false,
        id = 12101,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [205] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "boring",
        dirFollowObj = false,
        id = 205,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [31001] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 7000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "special1_1",
        dirFollowObj = false,
        id = 31001,
        audioRate = 0,
        hideShadow = true,
        offSet = {
        },
        beStand = true,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [206] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "special1",
        dirFollowObj = false,
        id = 206,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [31003] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 7000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "gunqiu",
        dirFollowObj = false,
        id = 31003,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = true,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [207] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "special2",
        dirFollowObj = false,
        id = 207,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [3003] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "wenquan",
        dirFollowObj = false,
        id = 3003,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [208] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "special3",
        dirFollowObj = false,
        id = 208,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [31007] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 6000,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "idle",
        dirFollowObj = false,
        id = 31007,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [12104] = {
        playCond = {
            playMix = 2,
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "play",
        dirFollowObj = false,
        id = 12104,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = true,
        motionRecourse_1 = "",
        audioRange = 0,
    },
    [910000] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "idle",
        audioId = 0,
        objectAction = "",
        dirFollowObj = false,
        id = 910000,
        audioRate = 0,
        hideShadow = false,
        offSet = {
            y = 35,
            x = 0,
        },
        beStand = false,
        motionActIsLoop = true,
        objectActIsLoop = false,
        motionRecourse_1 = "effect/SDeffectEquip/910001/SDeffect_910001",
        audioRange = 0,
    },
    [204] = {
        playCond = {
        },
        audioLoop = false,
        modelDir = 0,
        aiDelayTime = 0,
        motionAction_1 = "",
        audioId = 0,
        objectAction = "angry",
        dirFollowObj = false,
        id = 204,
        audioRate = 0,
        hideShadow = false,
        offSet = {
        },
        beStand = false,
        motionActIsLoop = false,
        objectActIsLoop = false,
        motionRecourse_1 = "",
        audioRange = 0,
    },
}