return {
    [1] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 1,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [2] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 2,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [3] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 3,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [4] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 4,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [5] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 5,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [6] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 6,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [7] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 7,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [10103] = {
        hintPreDes = 3101,
        hintEndAudio = 8105,
        hintStartAudio = 8104,
        id = 10103,
        hintStartEffect = "effect/world/UI_hintEvt/Hint_evt",
        hintEndEffect = "effect/world/UI_hintEvt/Hint_evt",
        hintEventDes = 3102,
    },
    [101] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 101,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [10104] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 10104,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [10105] = {
        hintPreDes = 3101,
        hintEndAudio = 8105,
        hintStartAudio = 8104,
        id = 10105,
        hintStartEffect = "effect/world/UI_hintEvt/Hint_evt",
        hintEndEffect = "effect/world/UI_hintEvt/Hint_evt",
        hintEventDes = 3102,
    },
    [10102] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 10102,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [10106] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 10106,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
    [102] = {
        hintPreDes = 0,
        hintEndAudio = 0,
        hintStartAudio = 0,
        id = 102,
        hintStartEffect = "",
        hintEndEffect = "",
        hintEventDes = 0,
    },
}