return {
    [1] = {
        id = 1,
        resourceType = 1,
        isSpecialModel = false,
        path = "ui/common/img_touming.png",
    },
    [1111] = {
        id = 1111,
        resourceType = 2,
        isSpecialModel = true,
        path = "modle/citymodle/city_10211/city_10211",
    },
    [401] = {
        id = 401,
        resourceType = 2,
        isSpecialModel = false,
        path = "",
    },
    [409] = {
        id = 409,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/lajitong/lajitong",
    },
    [413] = {
        id = 413,
        resourceType = 1,
        isSpecialModel = false,
        path = "citymap/world/object/build_pool/langan.png",
    },
    [2002] = {
        id = 2002,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/xiangbin/xiangbin",
    },
    [1114] = {
        id = 1114,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/citymodle/city_10509/city_10509",
    },
    [1115] = {
        id = 1115,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/citymodle/city_11307/city_11306",
    },
    [402] = {
        id = 402,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/dengta/dengta",
    },
    [204] = {
        id = 204,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/stage_middle/wutai3",
    },
    [2005] = {
        id = 2005,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/yibu/yibu",
    },
    [414] = {
        id = 414,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/chuanwu/chuanwu",
    },
    [210] = {
        id = 210,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/stage_left/wutai1",
    },
    [1101] = {
        id = 1101,
        resourceType = 1,
        isSpecialModel = false,
        path = "fightmap/world_catCafe/batai.png",
    },
    [2006] = {
        id = 2006,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/tiaozai/tiaozai",
    },
    [1102] = {
        id = 1102,
        resourceType = 1,
        isSpecialModel = false,
        path = "fightmap/world_catCafe/dengzi.png",
    },
    [2007] = {
        id = 2007,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/xiaobao/xiaobao",
    },
    [1103] = {
        id = 1103,
        resourceType = 1,
        isSpecialModel = false,
        path = "fightmap/world_catCafe/dengzi2.png",
    },
    [2008] = {
        id = 2008,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/xiaokaoji/xiaokaoji",
    },
    [403] = {
        id = 403,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/qiqiu/qiqiu",
    },
    [1104] = {
        id = 1104,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/wj_xiaoqiu/xiaoqiu",
    },
    [411] = {
        id = 411,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/xiaochouqiqiu/xiaochouqiqiu",
    },
    [415] = {
        id = 415,
        resourceType = 1,
        isSpecialModel = false,
        path = "citymap/world/object/build_pool/chair.png",
    },
    [1122] = {
        id = 1122,
        resourceType = 1,
        isSpecialModel = false,
        path = "fightmap/world_catCafe/maopajia.png",
    },
    [1121] = {
        id = 1121,
        resourceType = 1,
        isSpecialModel = false,
        path = "fightmap/world_catCafe/fanmaiji.png",
    },
    [1120] = {
        id = 1120,
        resourceType = 2,
        isSpecialModel = true,
        path = "modle/citymodle/city_11213/city_11213",
    },
    [1119] = {
        id = 1119,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/citymodle/city_10105/city_10105",
    },
    [1105] = {
        id = 1105,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/wj_hongqiu/hongqiu",
    },
    [2010] = {
        id = 2010,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/wangzai/wangzai",
    },
    [1118] = {
        id = 1118,
        resourceType = 2,
        isSpecialModel = true,
        path = "modle/citymodle/city_11009/city_11009",
    },
    [106] = {
        id = 106,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_shop/shangdian",
    },
    [2001] = {
        id = 2001,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/xiaobai/xiaobai",
    },
    [2013] = {
        id = 2013,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/xiaodao/shidao",
    },
    [208] = {
        id = 208,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/yaoma_konglong/tanhuangyaoma1",
    },
    [1116] = {
        id = 1116,
        resourceType = 2,
        isSpecialModel = true,
        path = "modle/citymodle/city_10708/city_10708",
    },
    [1106] = {
        id = 1106,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/wj_chuang/chuang",
    },
    [2011] = {
        id = 2011,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/daite/daite",
    },
    [206] = {
        id = 206,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/paizhao/heyinglipaixiong",
    },
    [1112] = {
        id = 1112,
        resourceType = 2,
        isSpecialModel = true,
        path = "modle/citymodle/city_10409/city_10409",
    },
    [412] = {
        id = 412,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/qiqiu/qiqiu",
    },
    [1113] = {
        id = 1113,
        resourceType = 2,
        isSpecialModel = true,
        path = "modle/citymodle/city_10308/city_10308",
    },
    [1117] = {
        id = 1117,
        resourceType = 2,
        isSpecialModel = true,
        path = "modle/citymodle/city_10808/city_10808",
    },
    [2003] = {
        id = 2003,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/dapang/dapang",
    },
    [1107] = {
        id = 1107,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/wj_haozi/haozi",
    },
    [2012] = {
        id = 2012,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/laiwu/laiwu",
    },
    [406] = {
        id = 406,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/ludeng/deng",
    },
    [202] = {
        id = 202,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_pool/youyongchi",
    },
    [1108] = {
        id = 1108,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/wj_doumaobang/doumaobang",
    },
    [410] = {
        id = 410,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/xiaofangshuan/xiaofangshuan",
    },
    [201] = {
        id = 201,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/qiaoqiaoban/qiaoqiaoban",
    },
    [102] = {
        id = 102,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_summon/kachijianzhu",
    },
    [408] = {
        id = 408,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/tree/shu",
    },
    [207] = {
        id = 207,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/yaoma_haitun/tanhuanyaoma2",
    },
    [105] = {
        id = 105,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_dress/shizhuangwu",
    },
    [211] = {
        id = 211,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/stage_right/wutai2",
    },
    [107] = {
        id = 107,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_astrology/zhanxingwu",
    },
    [301] = {
        id = 301,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/gitf_001/lihe",
    },
    [2009] = {
        id = 2009,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/qiaoqiao/qiaoqiao",
    },
    [2004] = {
        id = 2004,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/xiaolaomei/xiaolaomei",
    },
    [1109] = {
        id = 1109,
        resourceType = 1,
        isSpecialModel = false,
        path = "ui/common/img_touming.png",
    },
    [2014] = {
        id = 2014,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/xiaoke/xiaoke",
    },
    [203] = {
        id = 203,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/chuan/chuan",
    },
    [404] = {
        id = 404,
        resourceType = 2,
        isSpecialModel = false,
        path = "",
    },
    [205] = {
        id = 205,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/yizi/yizi",
    },
    [209] = {
        id = 209,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/qiuqian/qiuqian",
    },
    [101] = {
        id = 101,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_castle/xuyuanchengbao",
    },
    [103] = {
        id = 103,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_game/youxijianzhu",
    },
    [1110] = {
        id = 1110,
        resourceType = 1,
        isSpecialModel = false,
        path = "ui/common/img_touming.png",
    },
    [2015] = {
        id = 2015,
        resourceType = 2,
        isSpecialModel = false,
        path = "modle/cat/dahua/dahua",
    },
    [104] = {
        id = 104,
        resourceType = 2,
        isSpecialModel = false,
        path = "citymap/world/object/build_task/renwujianzhu",
    },
}